<?php
			$optionsArray = array( 'totals' => array( 'id_cont' => array( 'totalsType' => '' ),
'cont_hash' => array( 'totalsType' => '' ),
'cont_nit_contra_ta' => array( 'totalsType' => '' ),
'cont_paa_id' => array( 'totalsType' => '' ),
'cont_estado' => array( 'totalsType' => '' ),
'prenumero' => array( 'totalsType' => '' ),
'numregistro' => array( 'totalsType' => '' ),
'pre_contnumero' => array( 'totalsType' => '' ),
'contnumero' => array( 'totalsType' => '' ),
'cont_unspsc' => array( 'totalsType' => '' ),
'cont_tipo' => array( 'totalsType' => '' ),
'cont_ano' => array( 'totalsType' => '' ),
'cont_codrubro' => array( 'totalsType' => '' ),
'cont_tipo_rubro' => array( 'totalsType' => '' ),
'cont_reg_sigep' => array( 'totalsType' => '' ),
'cont_catalogo_presupuestal' => array( 'totalsType' => '' ),
'cont_tipopre' => array( 'totalsType' => '' ),
'cont_fechaapertura' => array( 'totalsType' => '' ),
'cont_plazoi' => array( 'totalsType' => '' ),
'cont_fecha_inicio' => array( 'totalsType' => '' ),
'cont_fechafinal' => array( 'totalsType' => '' ),
'cont_valormensual_base' => array( 'totalsType' => '' ),
'cont_valormensual_iva' => array( 'totalsType' => '' ),
'cont_fechavigencia' => array( 'totalsType' => '' ),
'cont_periodicidad' => array( 'totalsType' => '' ),
'cont_informessug' => array( 'totalsType' => '' ),
'cont_otrosi' => array( 'totalsType' => '' ),
'cont_otrosi_type' => array( 'totalsType' => '' ),
'cont_valorant' => array( 'totalsType' => '' ),
'cont_valorinicial' => array( 'totalsType' => '' ),
'cont_valormensual' => array( 'totalsType' => '' ),
'cont_valoradic_fecha' => array( 'totalsType' => '' ),
'cont_valoradic' => array( 'totalsType' => '' ),
'cont_valorreduc_fecha' => array( 'totalsType' => '' ),
'cont_valorreduc' => array( 'totalsType' => '' ),
'cont_valorvigente' => array( 'totalsType' => '' ),
'cont_valors' => array( 'totalsType' => '' ),
'cont_lugar' => array( 'totalsType' => '' ),
'cont_region' => array( 'totalsType' => '' ),
'cont_requactaliq' => array( 'totalsType' => '' ),
'cont_plazol' => array( 'totalsType' => '' ),
'cont_tipoproceso' => array( 'totalsType' => '' ),
'cont_formapago' => array( 'totalsType' => '' ),
'cont_tipoc' => array( 'totalsType' => '' ),
'cont_modalidad' => array( 'totalsType' => '' ),
'cont_causalc' => array( 'totalsType' => '' ),
'cont_funcion' => array( 'totalsType' => '' ),
'cesion_estado' => array( 'totalsType' => '' ),
'cont_acta_liquidacion' => array( 'totalsType' => '' ),
'cont_fecha_aprobgarantia' => array( 'totalsType' => '' ),
'cont_afilia_arl' => array( 'totalsType' => '' ),
'cont_excluir_notificacion' => array( 'totalsType' => '' ),
'cont_depsup' => array( 'totalsType' => '' ),
'cont_dep' => array( 'totalsType' => '' ),
'cont_lugar_prestacion' => array( 'totalsType' => '' ),
'cont_objeto' => array( 'totalsType' => '' ),
'cont_obligaciones' => array( 'totalsType' => '' ),
'cont_plazo' => array( 'totalsType' => '' ),
'cont_tipo_regimen' => array( 'totalsType' => '' ),
'cont_fecha_firma' => array( 'totalsType' => '' ),
'cont_secop_proceso' => array( 'totalsType' => '' ),
'cont_secop_enlace' => array( 'totalsType' => '' ),
'cont_sigep' => array( 'totalsType' => '' ),
'cont_vigencias_futuras' => array( 'totalsType' => '' ),
'vf_num_autorizacion' => array( 'totalsType' => '' ),
'vf_fecha' => array( 'totalsType' => '' ),
'vf_valor' => array( 'totalsType' => '' ),
'cont_fechasistema' => array( 'totalsType' => '' ),
'cont_cesion' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'id_cont',
'cont_hash',
'cont_nit_contra_ta',
'cont_paa_id',
'cont_cesion',
'cont_estado',
'prenumero',
'numregistro',
'pre_contnumero',
'contnumero',
'cont_tipo',
'cont_ano',
'cont_codrubro',
'cont_catalogo_presupuestal',
'cont_tipopre',
'cont_unspsc',
'cont_fechaapertura',
'cont_plazoi',
'cont_fecha_inicio',
'cont_fechafinal',
'cont_fechavigencia',
'cont_periodicidad',
'cont_informessug',
'cont_otrosi',
'cont_otrosi_type',
'cont_valorant',
'cont_valorinicial',
'cont_valormensual',
'cont_valoradic_fecha',
'cont_valoradic',
'cont_valorreduc_fecha',
'cont_valorreduc',
'cont_valorvigente',
'cont_valors',
'cont_lugar',
'cont_modalidad',
'cont_objeto',
'cont_region',
'cont_requactaliq',
'cont_plazol',
'cont_tipoproceso',
'cont_formapago',
'cont_tipo_rubro',
'cont_reg_sigep',
'cont_valormensual_base',
'cont_valormensual_iva',
'cont_tipoc',
'cont_fechasistema',
'cont_causalc',
'cont_acta_liquidacion',
'cont_excluir_notificacion',
'cont_funcion',
'cesion_estado',
'cont_fecha_aprobgarantia',
'cont_afilia_arl',
'cont_depsup',
'cont_dep',
'cont_lugar_prestacion',
'cont_obligaciones',
'cont_plazo',
'cont_tipo_regimen',
'cont_fecha_firma',
'cont_secop_proceso',
'cont_secop_enlace',
'cont_sigep',
'cont_vigencias_futuras',
'vf_num_autorizacion',
'vf_fecha',
'vf_valor' ),
'exportFields' => array( 'id_cont',
'cont_hash',
'cont_nit_contra_ta',
'cont_paa_id',
'cont_cesion',
'cont_estado',
'prenumero',
'numregistro',
'pre_contnumero',
'contnumero',
'cont_tipo',
'cont_ano',
'cont_codrubro',
'cont_catalogo_presupuestal',
'cont_tipopre',
'cont_fechaapertura',
'cont_plazoi',
'cont_fecha_inicio',
'cont_fechafinal',
'cont_fechavigencia',
'cont_periodicidad',
'cont_informessug',
'cont_otrosi',
'cont_otrosi_type',
'cont_valorant',
'cont_valorinicial',
'cont_valormensual',
'cont_valoradic_fecha',
'cont_valoradic',
'cont_valorreduc_fecha',
'cont_valorreduc',
'cont_valorvigente',
'cont_valors',
'cont_lugar',
'cont_modalidad',
'cont_objeto',
'cont_region',
'cont_requactaliq',
'cont_plazol',
'cont_tipoproceso',
'cont_formapago',
'cont_fechasistema',
'cont_acta_liquidacion',
'cont_excluir_notificacion',
'cont_unspsc',
'cont_tipo_rubro',
'cont_reg_sigep',
'cont_valormensual_base',
'cont_valormensual_iva',
'cont_tipoc',
'cont_causalc',
'cont_funcion',
'cesion_estado',
'cont_fecha_aprobgarantia',
'cont_afilia_arl',
'cont_depsup',
'cont_dep',
'cont_lugar_prestacion',
'cont_obligaciones',
'cont_plazo',
'cont_tipo_regimen',
'cont_fecha_firma',
'cont_secop_proceso',
'cont_secop_enlace',
'cont_sigep',
'cont_vigencias_futuras',
'vf_num_autorizacion',
'vf_fecha',
'vf_valor' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'id_cont' => array( 'export_field' ),
'cont_hash' => array( 'export_field1' ),
'cont_nit_contra_ta' => array( 'export_field2' ),
'cont_paa_id' => array( 'export_field3' ),
'cont_cesion' => array( 'export_field4' ),
'cont_estado' => array( 'export_field5' ),
'prenumero' => array( 'export_field6' ),
'numregistro' => array( 'export_field7' ),
'pre_contnumero' => array( 'export_field8' ),
'contnumero' => array( 'export_field9' ),
'cont_tipo' => array( 'export_field10' ),
'cont_ano' => array( 'export_field11' ),
'cont_codrubro' => array( 'export_field12' ),
'cont_catalogo_presupuestal' => array( 'export_field13' ),
'cont_tipopre' => array( 'export_field14' ),
'cont_unspsc' => array( 'export_field15' ),
'cont_fechaapertura' => array( 'export_field16' ),
'cont_plazoi' => array( 'export_field17' ),
'cont_fecha_inicio' => array( 'export_field18' ),
'cont_fechafinal' => array( 'export_field19' ),
'cont_fechavigencia' => array( 'export_field20' ),
'cont_periodicidad' => array( 'export_field21' ),
'cont_informessug' => array( 'export_field22' ),
'cont_otrosi' => array( 'export_field23' ),
'cont_otrosi_type' => array( 'export_field24' ),
'cont_valorant' => array( 'export_field25' ),
'cont_valorinicial' => array( 'export_field26' ),
'cont_valormensual' => array( 'export_field27' ),
'cont_valoradic_fecha' => array( 'export_field28' ),
'cont_valoradic' => array( 'export_field29' ),
'cont_valorreduc_fecha' => array( 'export_field30' ),
'cont_valorreduc' => array( 'export_field31' ),
'cont_valorvigente' => array( 'export_field32' ),
'cont_valors' => array( 'export_field33' ),
'cont_lugar' => array( 'export_field34' ),
'cont_modalidad' => array( 'export_field35' ),
'cont_objeto' => array( 'export_field36' ),
'cont_region' => array( 'export_field37' ),
'cont_requactaliq' => array( 'export_field38' ),
'cont_plazol' => array( 'export_field39' ),
'cont_tipoproceso' => array( 'export_field40' ),
'cont_formapago' => array( 'export_field41' ),
'cont_tipo_rubro' => array( 'export_field42' ),
'cont_reg_sigep' => array( 'export_field43' ),
'cont_valormensual_base' => array( 'export_field44' ),
'cont_valormensual_iva' => array( 'export_field45' ),
'cont_tipoc' => array( 'export_field46' ),
'cont_fechasistema' => array( 'export_field47' ),
'cont_causalc' => array( 'export_field48' ),
'cont_acta_liquidacion' => array( 'export_field49' ),
'cont_excluir_notificacion' => array( 'export_field50' ),
'cont_funcion' => array( 'export_field51' ),
'cesion_estado' => array( 'export_field52' ),
'cont_fecha_aprobgarantia' => array( 'export_field53' ),
'cont_afilia_arl' => array( 'export_field54' ),
'cont_depsup' => array( 'export_field55' ),
'cont_dep' => array( 'export_field56' ),
'cont_lugar_prestacion' => array( 'export_field57' ),
'cont_obligaciones' => array( 'export_field58' ),
'cont_plazo' => array( 'export_field59' ),
'cont_tipo_regimen' => array( 'export_field60' ),
'cont_fecha_firma' => array( 'export_field61' ),
'cont_secop_proceso' => array( 'export_field62' ),
'cont_secop_enlace' => array( 'export_field63' ),
'cont_sigep' => array( 'export_field64' ),
'cont_vigencias_futuras' => array( 'export_field65' ),
'vf_num_autorizacion' => array( 'export_field66' ),
'vf_fecha' => array( 'export_field67' ),
'vf_valor' => array( 'export_field68' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field23',
'export_field24',
'export_field25',
'export_field26',
'export_field27',
'export_field28',
'export_field29',
'export_field30',
'export_field31',
'export_field32',
'export_field33',
'export_field34',
'export_field35',
'export_field36',
'export_field37',
'export_field38',
'export_field39',
'export_field40',
'export_field41',
'export_field47',
'export_field49',
'export_field50',
'export_field15',
'export_field42',
'export_field43',
'export_field44',
'export_field45',
'export_field46',
'export_field48',
'export_field51',
'export_field52',
'export_field53',
'export_field54',
'export_field55',
'export_field56',
'export_field57',
'export_field58',
'export_field59',
'export_field60',
'export_field61',
'export_field62',
'export_field63',
'export_field64',
'export_field65',
'export_field66',
'export_field67',
'export_field68' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_field' => 'grid',
'export_field1' => 'grid',
'export_field2' => 'grid',
'export_field3' => 'grid',
'export_field4' => 'grid',
'export_field5' => 'grid',
'export_field6' => 'grid',
'export_field7' => 'grid',
'export_field8' => 'grid',
'export_field9' => 'grid',
'export_field10' => 'grid',
'export_field11' => 'grid',
'export_field12' => 'grid',
'export_field13' => 'grid',
'export_field14' => 'grid',
'export_field16' => 'grid',
'export_field17' => 'grid',
'export_field18' => 'grid',
'export_field19' => 'grid',
'export_field20' => 'grid',
'export_field21' => 'grid',
'export_field22' => 'grid',
'export_field23' => 'grid',
'export_field24' => 'grid',
'export_field25' => 'grid',
'export_field26' => 'grid',
'export_field27' => 'grid',
'export_field28' => 'grid',
'export_field29' => 'grid',
'export_field30' => 'grid',
'export_field31' => 'grid',
'export_field32' => 'grid',
'export_field33' => 'grid',
'export_field34' => 'grid',
'export_field35' => 'grid',
'export_field36' => 'grid',
'export_field37' => 'grid',
'export_field38' => 'grid',
'export_field39' => 'grid',
'export_field40' => 'grid',
'export_field41' => 'grid',
'export_field47' => 'grid',
'export_field49' => 'grid',
'export_field50' => 'grid',
'export_field15' => 'grid',
'export_field42' => 'grid',
'export_field43' => 'grid',
'export_field44' => 'grid',
'export_field45' => 'grid',
'export_field46' => 'grid',
'export_field48' => 'grid',
'export_field51' => 'grid',
'export_field52' => 'grid',
'export_field53' => 'grid',
'export_field54' => 'grid',
'export_field55' => 'grid',
'export_field56' => 'grid',
'export_field57' => 'grid',
'export_field58' => 'grid',
'export_field59' => 'grid',
'export_field60' => 'grid',
'export_field61' => 'grid',
'export_field62' => 'grid',
'export_field63' => 'grid',
'export_field64' => 'grid',
'export_field65' => 'grid',
'export_field66' => 'grid',
'export_field67' => 'grid',
'export_field68' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field23',
'export_field24',
'export_field25',
'export_field26',
'export_field27',
'export_field28',
'export_field29',
'export_field30',
'export_field31',
'export_field32',
'export_field33',
'export_field34',
'export_field35',
'export_field36',
'export_field37',
'export_field38',
'export_field39',
'export_field40',
'export_field41',
'export_field42',
'export_field43',
'export_field44',
'export_field45',
'export_field46',
'export_field47',
'export_field48',
'export_field49',
'export_field50',
'export_field51',
'export_field52',
'export_field53',
'export_field54',
'export_field55',
'export_field56',
'export_field57',
'export_field58',
'export_field59',
'export_field60',
'export_field61',
'export_field62',
'export_field63',
'export_field64',
'export_field65',
'export_field66',
'export_field67',
'export_field68' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => true,
'csv' => true,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field23',
'export_field24',
'export_field25',
'export_field26',
'export_field27',
'export_field28',
'export_field29',
'export_field30',
'export_field31',
'export_field32',
'export_field33',
'export_field34',
'export_field35',
'export_field36',
'export_field37',
'export_field38',
'export_field39',
'export_field40',
'export_field41',
'export_field47',
'export_field49',
'export_field50',
'export_field15',
'export_field42',
'export_field43',
'export_field44',
'export_field45',
'export_field46',
'export_field48',
'export_field51',
'export_field52',
'export_field53',
'export_field54',
'export_field55',
'export_field56',
'export_field57',
'export_field58',
'export_field59',
'export_field60',
'export_field61',
'export_field62',
'export_field63',
'export_field64',
'export_field65',
'export_field66',
'export_field67',
'export_field68' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field' => array( 'field' => 'id_cont',
'type' => 'export_field' ),
'export_field1' => array( 'field' => 'cont_hash',
'type' => 'export_field' ),
'export_field2' => array( 'field' => 'cont_nit_contra_ta',
'type' => 'export_field' ),
'export_field3' => array( 'field' => 'cont_paa_id',
'type' => 'export_field' ),
'export_field4' => array( 'field' => 'cont_cesion',
'type' => 'export_field' ),
'export_field5' => array( 'field' => 'cont_estado',
'type' => 'export_field' ),
'export_field6' => array( 'field' => 'prenumero',
'type' => 'export_field' ),
'export_field7' => array( 'field' => 'numregistro',
'type' => 'export_field' ),
'export_field8' => array( 'field' => 'pre_contnumero',
'type' => 'export_field' ),
'export_field9' => array( 'field' => 'contnumero',
'type' => 'export_field' ),
'export_field10' => array( 'field' => 'cont_tipo',
'type' => 'export_field' ),
'export_field11' => array( 'field' => 'cont_ano',
'type' => 'export_field' ),
'export_field12' => array( 'field' => 'cont_codrubro',
'type' => 'export_field' ),
'export_field13' => array( 'field' => 'cont_catalogo_presupuestal',
'type' => 'export_field' ),
'export_field14' => array( 'field' => 'cont_tipopre',
'type' => 'export_field' ),
'export_field15' => array( 'field' => 'cont_unspsc',
'type' => 'export_field' ),
'export_field16' => array( 'field' => 'cont_fechaapertura',
'type' => 'export_field' ),
'export_field17' => array( 'field' => 'cont_plazoi',
'type' => 'export_field' ),
'export_field18' => array( 'field' => 'cont_fecha_inicio',
'type' => 'export_field' ),
'export_field19' => array( 'field' => 'cont_fechafinal',
'type' => 'export_field' ),
'export_field20' => array( 'field' => 'cont_fechavigencia',
'type' => 'export_field' ),
'export_field21' => array( 'field' => 'cont_periodicidad',
'type' => 'export_field' ),
'export_field22' => array( 'field' => 'cont_informessug',
'type' => 'export_field' ),
'export_field23' => array( 'field' => 'cont_otrosi',
'type' => 'export_field' ),
'export_field24' => array( 'field' => 'cont_otrosi_type',
'type' => 'export_field' ),
'export_field25' => array( 'field' => 'cont_valorant',
'type' => 'export_field' ),
'export_field26' => array( 'field' => 'cont_valorinicial',
'type' => 'export_field' ),
'export_field27' => array( 'field' => 'cont_valormensual',
'type' => 'export_field' ),
'export_field28' => array( 'field' => 'cont_valoradic_fecha',
'type' => 'export_field' ),
'export_field29' => array( 'field' => 'cont_valoradic',
'type' => 'export_field' ),
'export_field30' => array( 'field' => 'cont_valorreduc_fecha',
'type' => 'export_field' ),
'export_field31' => array( 'field' => 'cont_valorreduc',
'type' => 'export_field' ),
'export_field32' => array( 'field' => 'cont_valorvigente',
'type' => 'export_field' ),
'export_field33' => array( 'field' => 'cont_valors',
'type' => 'export_field' ),
'export_field34' => array( 'field' => 'cont_lugar',
'type' => 'export_field' ),
'export_field35' => array( 'field' => 'cont_modalidad',
'type' => 'export_field' ),
'export_field36' => array( 'field' => 'cont_objeto',
'type' => 'export_field' ),
'export_field37' => array( 'field' => 'cont_region',
'type' => 'export_field' ),
'export_field38' => array( 'field' => 'cont_requactaliq',
'type' => 'export_field' ),
'export_field39' => array( 'field' => 'cont_plazol',
'type' => 'export_field' ),
'export_field40' => array( 'field' => 'cont_tipoproceso',
'type' => 'export_field' ),
'export_field41' => array( 'field' => 'cont_formapago',
'type' => 'export_field' ),
'export_field42' => array( 'field' => 'cont_tipo_rubro',
'type' => 'export_field' ),
'export_field43' => array( 'field' => 'cont_reg_sigep',
'type' => 'export_field' ),
'export_field44' => array( 'field' => 'cont_valormensual_base',
'type' => 'export_field' ),
'export_field45' => array( 'field' => 'cont_valormensual_iva',
'type' => 'export_field' ),
'export_field46' => array( 'field' => 'cont_tipoc',
'type' => 'export_field' ),
'export_field47' => array( 'field' => 'cont_fechasistema',
'type' => 'export_field' ),
'export_field48' => array( 'field' => 'cont_causalc',
'type' => 'export_field' ),
'export_field49' => array( 'field' => 'cont_acta_liquidacion',
'type' => 'export_field' ),
'export_field50' => array( 'field' => 'cont_excluir_notificacion',
'type' => 'export_field' ),
'export_field51' => array( 'field' => 'cont_funcion',
'type' => 'export_field' ),
'export_field52' => array( 'field' => 'cesion_estado',
'type' => 'export_field' ),
'export_field53' => array( 'field' => 'cont_fecha_aprobgarantia',
'type' => 'export_field' ),
'export_field54' => array( 'field' => 'cont_afilia_arl',
'type' => 'export_field' ),
'export_field55' => array( 'field' => 'cont_depsup',
'type' => 'export_field' ),
'export_field56' => array( 'field' => 'cont_dep',
'type' => 'export_field' ),
'export_field57' => array( 'field' => 'cont_lugar_prestacion',
'type' => 'export_field' ),
'export_field58' => array( 'field' => 'cont_obligaciones',
'type' => 'export_field' ),
'export_field59' => array( 'field' => 'cont_plazo',
'type' => 'export_field' ),
'export_field60' => array( 'field' => 'cont_tipo_regimen',
'type' => 'export_field' ),
'export_field61' => array( 'field' => 'cont_fecha_firma',
'type' => 'export_field' ),
'export_field62' => array( 'field' => 'cont_secop_proceso',
'type' => 'export_field' ),
'export_field63' => array( 'field' => 'cont_secop_enlace',
'type' => 'export_field' ),
'export_field64' => array( 'field' => 'cont_sigep',
'type' => 'export_field' ),
'export_field65' => array( 'field' => 'cont_vigencias_futuras',
'type' => 'export_field' ),
'export_field66' => array( 'field' => 'vf_num_autorizacion',
'type' => 'export_field' ),
'export_field67' => array( 'field' => 'vf_fecha',
'type' => 'export_field' ),
'export_field68' => array( 'field' => 'vf_valor',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 4,
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>