<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'id_cont',
'cont_hash',
'cont_nit_contra_ta',
'cont_paa_id',
'cont_cesion',
'cont_estado',
'prenumero',
'numregistro',
'pre_contnumero',
'contnumero',
'cont_tipo',
'cont_ano',
'cont_codrubro',
'cont_catalogo_presupuestal',
'cont_tipopre',
'cont_unspsc',
'cont_fechaapertura',
'cont_plazoi',
'cont_fecha_inicio',
'cont_fechafinal',
'cont_fechavigencia',
'cont_periodicidad',
'cont_informessug',
'cont_otrosi',
'cont_otrosi_type',
'cont_valorant',
'cont_valorinicial',
'cont_valormensual',
'cont_valoradic_fecha',
'cont_valoradic',
'cont_valorreduc_fecha',
'cont_valorreduc',
'cont_valorvigente',
'cont_valors',
'cont_lugar',
'cont_modalidad',
'cont_objeto',
'cont_region',
'cont_requactaliq',
'cont_plazol',
'cont_tipoproceso',
'cont_formapago',
'cont_tipo_rubro',
'cont_reg_sigep',
'cont_valormensual_base',
'cont_valormensual_iva',
'cont_tipoc',
'cont_fechasistema',
'cont_causalc',
'cont_acta_liquidacion',
'cont_excluir_notificacion',
'cont_funcion',
'cesion_estado',
'cont_fecha_aprobgarantia',
'cont_afilia_arl',
'cont_depsup',
'cont_dep',
'cont_lugar_prestacion',
'cont_obligaciones',
'cont_plazo',
'cont_tipo_regimen',
'cont_fecha_firma',
'cont_secop_proceso',
'cont_secop_enlace',
'cont_sigep',
'cont_vigencias_futuras',
'vf_num_autorizacion',
'vf_fecha',
'vf_valor' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'id_cont' => array( 'import_field' ),
'cont_hash' => array( 'import_field1' ),
'cont_nit_contra_ta' => array( 'import_field2' ),
'cont_paa_id' => array( 'import_field3' ),
'cont_cesion' => array( 'import_field4' ),
'cont_estado' => array( 'import_field5' ),
'prenumero' => array( 'import_field6' ),
'numregistro' => array( 'import_field7' ),
'pre_contnumero' => array( 'import_field8' ),
'contnumero' => array( 'import_field9' ),
'cont_tipo' => array( 'import_field10' ),
'cont_ano' => array( 'import_field11' ),
'cont_codrubro' => array( 'import_field12' ),
'cont_catalogo_presupuestal' => array( 'import_field13' ),
'cont_tipopre' => array( 'import_field14' ),
'cont_unspsc' => array( 'import_field15' ),
'cont_fechaapertura' => array( 'import_field16' ),
'cont_plazoi' => array( 'import_field17' ),
'cont_fecha_inicio' => array( 'import_field18' ),
'cont_fechafinal' => array( 'import_field19' ),
'cont_fechavigencia' => array( 'import_field20' ),
'cont_periodicidad' => array( 'import_field21' ),
'cont_informessug' => array( 'import_field22' ),
'cont_otrosi' => array( 'import_field23' ),
'cont_otrosi_type' => array( 'import_field24' ),
'cont_valorant' => array( 'import_field25' ),
'cont_valorinicial' => array( 'import_field26' ),
'cont_valormensual' => array( 'import_field27' ),
'cont_valoradic_fecha' => array( 'import_field28' ),
'cont_valoradic' => array( 'import_field29' ),
'cont_valorreduc_fecha' => array( 'import_field30' ),
'cont_valorreduc' => array( 'import_field31' ),
'cont_valorvigente' => array( 'import_field32' ),
'cont_valors' => array( 'import_field33' ),
'cont_lugar' => array( 'import_field34' ),
'cont_modalidad' => array( 'import_field35' ),
'cont_objeto' => array( 'import_field36' ),
'cont_region' => array( 'import_field37' ),
'cont_requactaliq' => array( 'import_field38' ),
'cont_plazol' => array( 'import_field39' ),
'cont_tipoproceso' => array( 'import_field40' ),
'cont_formapago' => array( 'import_field41' ),
'cont_tipo_rubro' => array( 'import_field42' ),
'cont_reg_sigep' => array( 'import_field43' ),
'cont_valormensual_base' => array( 'import_field44' ),
'cont_valormensual_iva' => array( 'import_field45' ),
'cont_tipoc' => array( 'import_field46' ),
'cont_fechasistema' => array( 'import_field47' ),
'cont_causalc' => array( 'import_field48' ),
'cont_acta_liquidacion' => array( 'import_field49' ),
'cont_excluir_notificacion' => array( 'import_field50' ),
'cont_funcion' => array( 'import_field51' ),
'cesion_estado' => array( 'import_field52' ),
'cont_fecha_aprobgarantia' => array( 'import_field53' ),
'cont_afilia_arl' => array( 'import_field54' ),
'cont_depsup' => array( 'import_field55' ),
'cont_dep' => array( 'import_field56' ),
'cont_lugar_prestacion' => array( 'import_field57' ),
'cont_obligaciones' => array( 'import_field58' ),
'cont_plazo' => array( 'import_field59' ),
'cont_tipo_regimen' => array( 'import_field60' ),
'cont_fecha_firma' => array( 'import_field61' ),
'cont_secop_proceso' => array( 'import_field62' ),
'cont_secop_enlace' => array( 'import_field63' ),
'cont_sigep' => array( 'import_field64' ),
'cont_vigencias_futuras' => array( 'import_field65' ),
'vf_num_autorizacion' => array( 'import_field66' ),
'vf_fecha' => array( 'import_field67' ),
'vf_valor' => array( 'import_field68' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'import_header' ),
'grid' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field20',
'import_field21',
'import_field22',
'import_field23',
'import_field24',
'import_field25',
'import_field26',
'import_field27',
'import_field28',
'import_field29',
'import_field30',
'import_field31',
'import_field32',
'import_field33',
'import_field34',
'import_field35',
'import_field36',
'import_field37',
'import_field38',
'import_field39',
'import_field40',
'import_field41',
'import_field47',
'import_field49',
'import_field50',
'import_field15',
'import_field42',
'import_field43',
'import_field44',
'import_field45',
'import_field46',
'import_field48',
'import_field51',
'import_field52',
'import_field53',
'import_field54',
'import_field55',
'import_field56',
'import_field57',
'import_field58',
'import_field59',
'import_field60',
'import_field61',
'import_field62',
'import_field63',
'import_field64',
'import_field65',
'import_field66',
'import_field67',
'import_field68' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'import_header' => 'top',
'import_field' => 'grid',
'import_field1' => 'grid',
'import_field2' => 'grid',
'import_field3' => 'grid',
'import_field4' => 'grid',
'import_field5' => 'grid',
'import_field6' => 'grid',
'import_field7' => 'grid',
'import_field8' => 'grid',
'import_field9' => 'grid',
'import_field10' => 'grid',
'import_field11' => 'grid',
'import_field12' => 'grid',
'import_field13' => 'grid',
'import_field14' => 'grid',
'import_field16' => 'grid',
'import_field17' => 'grid',
'import_field18' => 'grid',
'import_field19' => 'grid',
'import_field20' => 'grid',
'import_field21' => 'grid',
'import_field22' => 'grid',
'import_field23' => 'grid',
'import_field24' => 'grid',
'import_field25' => 'grid',
'import_field26' => 'grid',
'import_field27' => 'grid',
'import_field28' => 'grid',
'import_field29' => 'grid',
'import_field30' => 'grid',
'import_field31' => 'grid',
'import_field32' => 'grid',
'import_field33' => 'grid',
'import_field34' => 'grid',
'import_field35' => 'grid',
'import_field36' => 'grid',
'import_field37' => 'grid',
'import_field38' => 'grid',
'import_field39' => 'grid',
'import_field40' => 'grid',
'import_field41' => 'grid',
'import_field47' => 'grid',
'import_field49' => 'grid',
'import_field50' => 'grid',
'import_field15' => 'grid',
'import_field42' => 'grid',
'import_field43' => 'grid',
'import_field44' => 'grid',
'import_field45' => 'grid',
'import_field46' => 'grid',
'import_field48' => 'grid',
'import_field51' => 'grid',
'import_field52' => 'grid',
'import_field53' => 'grid',
'import_field54' => 'grid',
'import_field55' => 'grid',
'import_field56' => 'grid',
'import_field57' => 'grid',
'import_field58' => 'grid',
'import_field59' => 'grid',
'import_field60' => 'grid',
'import_field61' => 'grid',
'import_field62' => 'grid',
'import_field63' => 'grid',
'import_field64' => 'grid',
'import_field65' => 'grid',
'import_field66' => 'grid',
'import_field67' => 'grid',
'import_field68' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'import_header' => array( 'import_header' ),
'import_field' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field20',
'import_field21',
'import_field22',
'import_field23',
'import_field24',
'import_field25',
'import_field26',
'import_field27',
'import_field28',
'import_field29',
'import_field30',
'import_field31',
'import_field32',
'import_field33',
'import_field34',
'import_field35',
'import_field36',
'import_field37',
'import_field38',
'import_field39',
'import_field40',
'import_field41',
'import_field42',
'import_field43',
'import_field44',
'import_field45',
'import_field46',
'import_field47',
'import_field48',
'import_field49',
'import_field50',
'import_field51',
'import_field52',
'import_field53',
'import_field54',
'import_field55',
'import_field56',
'import_field57',
'import_field58',
'import_field59',
'import_field60',
'import_field61',
'import_field62',
'import_field63',
'import_field64',
'import_field65',
'import_field66',
'import_field67',
'import_field68' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'import',
'type' => 'import',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'import-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'import-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field20',
'import_field21',
'import_field22',
'import_field23',
'import_field24',
'import_field25',
'import_field26',
'import_field27',
'import_field28',
'import_field29',
'import_field30',
'import_field31',
'import_field32',
'import_field33',
'import_field34',
'import_field35',
'import_field36',
'import_field37',
'import_field38',
'import_field39',
'import_field40',
'import_field41',
'import_field47',
'import_field49',
'import_field50',
'import_field15',
'import_field42',
'import_field43',
'import_field44',
'import_field45',
'import_field46',
'import_field48',
'import_field51',
'import_field52',
'import_field53',
'import_field54',
'import_field55',
'import_field56',
'import_field57',
'import_field58',
'import_field59',
'import_field60',
'import_field61',
'import_field62',
'import_field63',
'import_field64',
'import_field65',
'import_field66',
'import_field67',
'import_field68' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'import_header' => array( 'type' => 'import_header' ),
'import_field' => array( 'field' => 'id_cont',
'type' => 'import_field' ),
'import_field1' => array( 'field' => 'cont_hash',
'type' => 'import_field' ),
'import_field2' => array( 'field' => 'cont_nit_contra_ta',
'type' => 'import_field' ),
'import_field3' => array( 'field' => 'cont_paa_id',
'type' => 'import_field' ),
'import_field4' => array( 'field' => 'cont_cesion',
'type' => 'import_field' ),
'import_field5' => array( 'field' => 'cont_estado',
'type' => 'import_field' ),
'import_field6' => array( 'field' => 'prenumero',
'type' => 'import_field' ),
'import_field7' => array( 'field' => 'numregistro',
'type' => 'import_field' ),
'import_field8' => array( 'field' => 'pre_contnumero',
'type' => 'import_field' ),
'import_field9' => array( 'field' => 'contnumero',
'type' => 'import_field' ),
'import_field10' => array( 'field' => 'cont_tipo',
'type' => 'import_field' ),
'import_field11' => array( 'field' => 'cont_ano',
'type' => 'import_field' ),
'import_field12' => array( 'field' => 'cont_codrubro',
'type' => 'import_field' ),
'import_field13' => array( 'field' => 'cont_catalogo_presupuestal',
'type' => 'import_field' ),
'import_field14' => array( 'field' => 'cont_tipopre',
'type' => 'import_field' ),
'import_field15' => array( 'field' => 'cont_unspsc',
'type' => 'import_field' ),
'import_field16' => array( 'field' => 'cont_fechaapertura',
'type' => 'import_field' ),
'import_field17' => array( 'field' => 'cont_plazoi',
'type' => 'import_field' ),
'import_field18' => array( 'field' => 'cont_fecha_inicio',
'type' => 'import_field' ),
'import_field19' => array( 'field' => 'cont_fechafinal',
'type' => 'import_field' ),
'import_field20' => array( 'field' => 'cont_fechavigencia',
'type' => 'import_field' ),
'import_field21' => array( 'field' => 'cont_periodicidad',
'type' => 'import_field' ),
'import_field22' => array( 'field' => 'cont_informessug',
'type' => 'import_field' ),
'import_field23' => array( 'field' => 'cont_otrosi',
'type' => 'import_field' ),
'import_field24' => array( 'field' => 'cont_otrosi_type',
'type' => 'import_field' ),
'import_field25' => array( 'field' => 'cont_valorant',
'type' => 'import_field' ),
'import_field26' => array( 'field' => 'cont_valorinicial',
'type' => 'import_field' ),
'import_field27' => array( 'field' => 'cont_valormensual',
'type' => 'import_field' ),
'import_field28' => array( 'field' => 'cont_valoradic_fecha',
'type' => 'import_field' ),
'import_field29' => array( 'field' => 'cont_valoradic',
'type' => 'import_field' ),
'import_field30' => array( 'field' => 'cont_valorreduc_fecha',
'type' => 'import_field' ),
'import_field31' => array( 'field' => 'cont_valorreduc',
'type' => 'import_field' ),
'import_field32' => array( 'field' => 'cont_valorvigente',
'type' => 'import_field' ),
'import_field33' => array( 'field' => 'cont_valors',
'type' => 'import_field' ),
'import_field34' => array( 'field' => 'cont_lugar',
'type' => 'import_field' ),
'import_field35' => array( 'field' => 'cont_modalidad',
'type' => 'import_field' ),
'import_field36' => array( 'field' => 'cont_objeto',
'type' => 'import_field' ),
'import_field37' => array( 'field' => 'cont_region',
'type' => 'import_field' ),
'import_field38' => array( 'field' => 'cont_requactaliq',
'type' => 'import_field' ),
'import_field39' => array( 'field' => 'cont_plazol',
'type' => 'import_field' ),
'import_field40' => array( 'field' => 'cont_tipoproceso',
'type' => 'import_field' ),
'import_field41' => array( 'field' => 'cont_formapago',
'type' => 'import_field' ),
'import_field42' => array( 'field' => 'cont_tipo_rubro',
'type' => 'import_field' ),
'import_field43' => array( 'field' => 'cont_reg_sigep',
'type' => 'import_field' ),
'import_field44' => array( 'field' => 'cont_valormensual_base',
'type' => 'import_field' ),
'import_field45' => array( 'field' => 'cont_valormensual_iva',
'type' => 'import_field' ),
'import_field46' => array( 'field' => 'cont_tipoc',
'type' => 'import_field' ),
'import_field47' => array( 'field' => 'cont_fechasistema',
'type' => 'import_field' ),
'import_field48' => array( 'field' => 'cont_causalc',
'type' => 'import_field' ),
'import_field49' => array( 'field' => 'cont_acta_liquidacion',
'type' => 'import_field' ),
'import_field50' => array( 'field' => 'cont_excluir_notificacion',
'type' => 'import_field' ),
'import_field51' => array( 'field' => 'cont_funcion',
'type' => 'import_field' ),
'import_field52' => array( 'field' => 'cesion_estado',
'type' => 'import_field' ),
'import_field53' => array( 'field' => 'cont_fecha_aprobgarantia',
'type' => 'import_field' ),
'import_field54' => array( 'field' => 'cont_afilia_arl',
'type' => 'import_field' ),
'import_field55' => array( 'field' => 'cont_depsup',
'type' => 'import_field' ),
'import_field56' => array( 'field' => 'cont_dep',
'type' => 'import_field' ),
'import_field57' => array( 'field' => 'cont_lugar_prestacion',
'type' => 'import_field' ),
'import_field58' => array( 'field' => 'cont_obligaciones',
'type' => 'import_field' ),
'import_field59' => array( 'field' => 'cont_plazo',
'type' => 'import_field' ),
'import_field60' => array( 'field' => 'cont_tipo_regimen',
'type' => 'import_field' ),
'import_field61' => array( 'field' => 'cont_fecha_firma',
'type' => 'import_field' ),
'import_field62' => array( 'field' => 'cont_secop_proceso',
'type' => 'import_field' ),
'import_field63' => array( 'field' => 'cont_secop_enlace',
'type' => 'import_field' ),
'import_field64' => array( 'field' => 'cont_sigep',
'type' => 'import_field' ),
'import_field65' => array( 'field' => 'cont_vigencias_futuras',
'type' => 'import_field' ),
'import_field66' => array( 'field' => 'vf_num_autorizacion',
'type' => 'import_field' ),
'import_field67' => array( 'field' => 'vf_fecha',
'type' => 'import_field' ),
'import_field68' => array( 'field' => 'vf_valor',
'type' => 'import_field' ) ),
'dbProps' => array(  ),
'version' => 4 );
		?>