<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'ACT_ID_FK',
'UEJ',
'RUBRO',
'ACTIVIDAD',
'RECURSOS_SOLICITADOS',
'FECHA_REG',
'USER_REG',
'TIPO',
'EBI',
'SYS_STATUS',
'PROYECTO',
'USO_CONTABILIDAD_A',
'USO_CONTABILIDAD_B',
'CATALOGO_PRESUPUESTAL_COD' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'ACT_ID_FK' => array( 'import_field2' ),
'UEJ' => array( 'import_field3' ),
'RUBRO' => array( 'import_field4' ),
'ACTIVIDAD' => array( 'import_field8' ),
'RECURSOS_SOLICITADOS' => array( 'import_field10' ),
'FECHA_REG' => array( 'import_field11' ),
'USER_REG' => array( 'import_field12' ),
'TIPO' => array( 'import_field' ),
'EBI' => array( 'import_field6' ),
'SYS_STATUS' => array( 'import_field7' ),
'PROYECTO' => array( 'import_field1' ),
'USO_CONTABILIDAD_A' => array( 'import_field5' ),
'USO_CONTABILIDAD_B' => array( 'import_field9' ),
'CATALOGO_PRESUPUESTAL_COD' => array( 'import_field13' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'import_header' ),
'grid' => array( 'import_field2',
'import_field3',
'import_field4',
'import_field8',
'import_field10',
'import_field11',
'import_field12',
'import_field',
'import_field6',
'import_field7',
'import_field1',
'import_field5',
'import_field9',
'import_field13' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'import_header' => 'top',
'import_field2' => 'grid',
'import_field3' => 'grid',
'import_field4' => 'grid',
'import_field8' => 'grid',
'import_field10' => 'grid',
'import_field11' => 'grid',
'import_field12' => 'grid',
'import_field' => 'grid',
'import_field6' => 'grid',
'import_field7' => 'grid',
'import_field1' => 'grid',
'import_field5' => 'grid',
'import_field9' => 'grid',
'import_field13' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'import_header' => array( 'import_header' ),
'import_field' => array( 'import_field2',
'import_field3',
'import_field4',
'import_field8',
'import_field10',
'import_field11',
'import_field12',
'import_field',
'import_field6',
'import_field7',
'import_field1',
'import_field5',
'import_field9',
'import_field13' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'import',
'type' => 'import',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'import-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'import-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_field2',
'import_field3',
'import_field4',
'import_field8',
'import_field10',
'import_field11',
'import_field12',
'import_field',
'import_field6',
'import_field7',
'import_field1',
'import_field5',
'import_field9',
'import_field13' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'import_header' => array( 'type' => 'import_header' ),
'import_field2' => array( 'field' => 'ACT_ID_FK',
'type' => 'import_field' ),
'import_field3' => array( 'field' => 'UEJ',
'type' => 'import_field' ),
'import_field4' => array( 'field' => 'RUBRO',
'type' => 'import_field' ),
'import_field8' => array( 'field' => 'ACTIVIDAD',
'type' => 'import_field' ),
'import_field10' => array( 'field' => 'RECURSOS_SOLICITADOS',
'type' => 'import_field' ),
'import_field11' => array( 'field' => 'FECHA_REG',
'type' => 'import_field' ),
'import_field12' => array( 'field' => 'USER_REG',
'type' => 'import_field' ),
'import_field' => array( 'field' => 'TIPO',
'type' => 'import_field' ),
'import_field6' => array( 'field' => 'EBI',
'type' => 'import_field' ),
'import_field7' => array( 'field' => 'SYS_STATUS',
'type' => 'import_field' ),
'import_field1' => array( 'field' => 'PROYECTO',
'type' => 'import_field' ),
'import_field5' => array( 'field' => 'USO_CONTABILIDAD_A',
'type' => 'import_field' ),
'import_field9' => array( 'field' => 'USO_CONTABILIDAD_B',
'type' => 'import_field' ),
'import_field13' => array( 'field' => 'CATALOGO_PRESUPUESTAL_COD',
'type' => 'import_field' ) ),
'dbProps' => array(  ),
'version' => 4 );
		?>