<?php
			$optionsArray = array( 'totals' => array( 'PAAU_ID' => array( 'totalsType' => '' ),
'PAA_ID_FK' => array( 'totalsType' => '' ),
'SOL_FECHA' => array( 'totalsType' => '' ),
'SOL_DEPENDENCIA' => array( 'totalsType' => '' ),
'OPERACION_ID_FK' => array( 'totalsType' => '' ),
'USER_REG' => array( 'totalsType' => '' ),
'SYS_STATUS' => array( 'totalsType' => '' ),
'NUMERO_SCDP_SIIF' => array( 'totalsType' => '' ),
'DOCUMENTO_SCDP_SIIF' => array( 'totalsType' => '' ),
'FECHA_SCDP_SIIF' => array( 'totalsType' => '' ),
'USUARIO_SCDP_SIIF' => array( 'totalsType' => '' ),
'TIPO_SOL' => array( 'totalsType' => '' ),
'DEV_FECHA' => array( 'totalsType' => '' ),
'DEV_USER' => array( 'totalsType' => '' ),
'DEV_MSG' => array( 'totalsType' => '' ),
'DEV_MAIL' => array( 'totalsType' => '' ),
'FECHA_REG' => array( 'totalsType' => '' ),
'VALOR_SOLICITADO' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'PAAU_ID',
'PAA_ID_FK',
'SOL_FECHA',
'SOL_DEPENDENCIA',
'OPERACION_ID_FK',
'USER_REG',
'SYS_STATUS',
'TIPO_SOL',
'DOCUMENTO_SCDP_SIIF',
'FECHA_SCDP_SIIF',
'USUARIO_SCDP_SIIF',
'DEV_FECHA',
'DEV_USER',
'DEV_MSG',
'DEV_MAIL',
'FECHA_REG',
'VALOR_SOLICITADO' ),
'exportFields' => array( 'PAAU_ID',
'PAA_ID_FK',
'SOL_FECHA',
'SOL_DEPENDENCIA',
'OPERACION_ID_FK',
'USER_REG',
'SYS_STATUS',
'TIPO_SOL',
'DOCUMENTO_SCDP_SIIF',
'FECHA_SCDP_SIIF',
'USUARIO_SCDP_SIIF',
'DEV_FECHA',
'DEV_USER',
'DEV_MSG',
'DEV_MAIL',
'FECHA_REG',
'VALOR_SOLICITADO' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'PAAU_ID' => array( 'export_field' ),
'PAA_ID_FK' => array( 'export_field1' ),
'SOL_FECHA' => array( 'export_field2' ),
'SOL_DEPENDENCIA' => array( 'export_field3' ),
'OPERACION_ID_FK' => array( 'export_field4' ),
'USER_REG' => array( 'export_field21' ),
'SYS_STATUS' => array( 'export_field22' ),
'TIPO_SOL' => array( 'export_field5' ),
'DOCUMENTO_SCDP_SIIF' => array( 'export_field6' ),
'FECHA_SCDP_SIIF' => array( 'export_field7' ),
'USUARIO_SCDP_SIIF' => array( 'export_field8' ),
'DEV_FECHA' => array( 'export_field9' ),
'DEV_USER' => array( 'export_field10' ),
'DEV_MSG' => array( 'export_field11' ),
'DEV_MAIL' => array( 'export_field12' ),
'FECHA_REG' => array( 'export_field13' ),
'VALOR_SOLICITADO' => array( 'export_field14' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field21',
'export_field22',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_field' => 'grid',
'export_field1' => 'grid',
'export_field2' => 'grid',
'export_field3' => 'grid',
'export_field4' => 'grid',
'export_field21' => 'grid',
'export_field22' => 'grid',
'export_field5' => 'grid',
'export_field6' => 'grid',
'export_field7' => 'grid',
'export_field8' => 'grid',
'export_field9' => 'grid',
'export_field10' => 'grid',
'export_field11' => 'grid',
'export_field12' => 'grid',
'export_field13' => 'grid',
'export_field14' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field21',
'export_field22',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => true,
'csv' => true,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field21',
'export_field22',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field' => array( 'field' => 'PAAU_ID',
'type' => 'export_field' ),
'export_field1' => array( 'field' => 'PAA_ID_FK',
'type' => 'export_field' ),
'export_field2' => array( 'field' => 'SOL_FECHA',
'type' => 'export_field' ),
'export_field3' => array( 'field' => 'SOL_DEPENDENCIA',
'type' => 'export_field' ),
'export_field4' => array( 'field' => 'OPERACION_ID_FK',
'type' => 'export_field' ),
'export_field21' => array( 'field' => 'USER_REG',
'type' => 'export_field' ),
'export_field22' => array( 'field' => 'SYS_STATUS',
'type' => 'export_field' ),
'export_field5' => array( 'field' => 'TIPO_SOL',
'type' => 'export_field' ),
'export_field6' => array( 'field' => 'DOCUMENTO_SCDP_SIIF',
'type' => 'export_field' ),
'export_field7' => array( 'field' => 'FECHA_SCDP_SIIF',
'type' => 'export_field' ),
'export_field8' => array( 'field' => 'USUARIO_SCDP_SIIF',
'type' => 'export_field' ),
'export_field9' => array( 'field' => 'DEV_FECHA',
'type' => 'export_field' ),
'export_field10' => array( 'field' => 'DEV_USER',
'type' => 'export_field' ),
'export_field11' => array( 'field' => 'DEV_MSG',
'type' => 'export_field' ),
'export_field12' => array( 'field' => 'DEV_MAIL',
'type' => 'export_field' ),
'export_field13' => array( 'field' => 'FECHA_REG',
'type' => 'export_field' ),
'export_field14' => array( 'field' => 'VALOR_SOLICITADO',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 4,
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>