<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'PAAU_ID',
'PAA_ID_FK',
'SOL_FECHA',
'SOL_DEPENDENCIA',
'OPERACION_ID_FK',
'USER_REG',
'SYS_STATUS',
'NUMERO_SCDP_SIIF',
'DOCUMENTO_SCDP_SIIF',
'FECHA_SCDP_SIIF',
'USUARIO_SCDP_SIIF',
'DEV_FECHA',
'DEV_USER',
'DEV_MSG',
'DEV_MAIL' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'PAAU_ID' => array( 'import_field' ),
'PAA_ID_FK' => array( 'import_field1' ),
'SOL_FECHA' => array( 'import_field2' ),
'SOL_DEPENDENCIA' => array( 'import_field3' ),
'OPERACION_ID_FK' => array( 'import_field4' ),
'USER_REG' => array( 'import_field21' ),
'SYS_STATUS' => array( 'import_field22' ),
'NUMERO_SCDP_SIIF' => array( 'import_field5' ),
'DOCUMENTO_SCDP_SIIF' => array( 'import_field6' ),
'FECHA_SCDP_SIIF' => array( 'import_field7' ),
'USUARIO_SCDP_SIIF' => array( 'import_field8' ),
'DEV_FECHA' => array( 'import_field9' ),
'DEV_USER' => array( 'import_field10' ),
'DEV_MSG' => array( 'import_field11' ),
'DEV_MAIL' => array( 'import_field12' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'import_header' ),
'grid' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field21',
'import_field22',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'import_header' => 'top',
'import_field' => 'grid',
'import_field1' => 'grid',
'import_field2' => 'grid',
'import_field3' => 'grid',
'import_field4' => 'grid',
'import_field21' => 'grid',
'import_field22' => 'grid',
'import_field5' => 'grid',
'import_field6' => 'grid',
'import_field7' => 'grid',
'import_field8' => 'grid',
'import_field9' => 'grid',
'import_field10' => 'grid',
'import_field11' => 'grid',
'import_field12' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'import_header' => array( 'import_header' ),
'import_field' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field21',
'import_field22',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'import',
'type' => 'import',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'import-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'import-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field21',
'import_field22',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'import_header' => array( 'type' => 'import_header' ),
'import_field' => array( 'field' => 'PAAU_ID',
'type' => 'import_field' ),
'import_field1' => array( 'field' => 'PAA_ID_FK',
'type' => 'import_field' ),
'import_field2' => array( 'field' => 'SOL_FECHA',
'type' => 'import_field' ),
'import_field3' => array( 'field' => 'SOL_DEPENDENCIA',
'type' => 'import_field' ),
'import_field4' => array( 'field' => 'OPERACION_ID_FK',
'type' => 'import_field' ),
'import_field21' => array( 'field' => 'USER_REG',
'type' => 'import_field' ),
'import_field22' => array( 'field' => 'SYS_STATUS',
'type' => 'import_field' ),
'import_field5' => array( 'field' => 'NUMERO_SCDP_SIIF',
'type' => 'import_field' ),
'import_field6' => array( 'field' => 'DOCUMENTO_SCDP_SIIF',
'type' => 'import_field' ),
'import_field7' => array( 'field' => 'FECHA_SCDP_SIIF',
'type' => 'import_field' ),
'import_field8' => array( 'field' => 'USUARIO_SCDP_SIIF',
'type' => 'import_field' ),
'import_field9' => array( 'field' => 'DEV_FECHA',
'type' => 'import_field' ),
'import_field10' => array( 'field' => 'DEV_USER',
'type' => 'import_field' ),
'import_field11' => array( 'field' => 'DEV_MSG',
'type' => 'import_field' ),
'import_field12' => array( 'field' => 'DEV_MAIL',
'type' => 'import_field' ) ),
'dbProps' => array(  ),
'version' => 4 );
		?>