<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'PAA_ID',
'DESCRIPCION',
'FUENTE_RECURSOS',
'VALOR',
'COD_UBICACION',
'responsable',
'vigencia',
'sys_user',
'sys_status',
'TIPOSOL',
'USOS_TOTAL' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'PAA_ID' => array( 'import_field' ),
'DESCRIPCION' => array( 'import_field2' ),
'FUENTE_RECURSOS' => array( 'import_field9' ),
'VALOR' => array( 'import_field10' ),
'COD_UBICACION' => array( 'import_field15' ),
'responsable' => array( 'import_field19' ),
'vigencia' => array( 'import_field20' ),
'sys_user' => array( 'import_field21' ),
'sys_status' => array( 'import_field23' ),
'TIPOSOL' => array( 'import_field1' ),
'USOS_TOTAL' => array( 'import_field3' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'import_header' ),
'grid' => array( 'import_field',
'import_field2',
'import_field9',
'import_field10',
'import_field15',
'import_field19',
'import_field20',
'import_field21',
'import_field23',
'import_field1',
'import_field3' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'import_header' => 'top',
'import_field' => 'grid',
'import_field2' => 'grid',
'import_field9' => 'grid',
'import_field10' => 'grid',
'import_field15' => 'grid',
'import_field19' => 'grid',
'import_field20' => 'grid',
'import_field21' => 'grid',
'import_field23' => 'grid',
'import_field1' => 'grid',
'import_field3' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'import_header' => array( 'import_header' ),
'import_field' => array( 'import_field',
'import_field2',
'import_field9',
'import_field10',
'import_field15',
'import_field19',
'import_field20',
'import_field21',
'import_field23',
'import_field1',
'import_field3' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'import',
'type' => 'import',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'import-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'import-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_field',
'import_field2',
'import_field9',
'import_field10',
'import_field15',
'import_field19',
'import_field20',
'import_field21',
'import_field23',
'import_field1',
'import_field3' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'import_header' => array( 'type' => 'import_header' ),
'import_field' => array( 'field' => 'PAA_ID',
'type' => 'import_field' ),
'import_field2' => array( 'field' => 'DESCRIPCION',
'type' => 'import_field' ),
'import_field9' => array( 'field' => 'FUENTE_RECURSOS',
'type' => 'import_field' ),
'import_field10' => array( 'field' => 'VALOR',
'type' => 'import_field' ),
'import_field15' => array( 'field' => 'COD_UBICACION',
'type' => 'import_field' ),
'import_field19' => array( 'field' => 'responsable',
'type' => 'import_field' ),
'import_field20' => array( 'field' => 'vigencia',
'type' => 'import_field' ),
'import_field21' => array( 'field' => 'sys_user',
'type' => 'import_field' ),
'import_field23' => array( 'field' => 'sys_status',
'type' => 'import_field' ),
'import_field1' => array( 'field' => 'TIPOSOL',
'type' => 'import_field' ),
'import_field3' => array( 'field' => 'USOS_TOTAL',
'type' => 'import_field' ) ),
'dbProps' => array(  ),
'version' => 4 );
		?>