<?php
			$optionsArray = array( 'list' => array( 'inlineAdd' => false,
'detailsAdd' => true,
'inlineEdit' => false,
'delete' => true,
'updateSelected' => false,
'addInPopup' => false,
'editInPopup' => true,
'viewInPopup' => true,
'clickSort' => true,
'sortDropdown' => false,
'showHideFields' => false,
'reorderFields' => false ),
'master' => array( 'global_operacion' => array( 'preview' => true ) ),
'listSearch' => array( 'alwaysOnPanelFields' => array( 'PAA_ID_FK',
'SOL_DEPENDENCIA',
'USER_REG' ),
'searchPanel' => true,
'fixedSearchPanel' => false,
'simpleSearchOptions' => false,
'searchSaving' => false ),
'totals' => array( 'PAAU_ID' => array( 'totalsType' => '' ),
'PAA_ID_FK' => array( 'totalsType' => '' ),
'SOL_FECHA' => array( 'totalsType' => '' ),
'SOL_DEPENDENCIA' => array( 'totalsType' => '' ),
'OPERACION_ID_FK' => array( 'totalsType' => '' ),
'USER_REG' => array( 'totalsType' => '' ),
'SYS_STATUS' => array( 'totalsType' => '' ),
'NUMERO_SCDP_SIIF' => array( 'totalsType' => '' ),
'DOCUMENTO_SCDP_SIIF' => array( 'totalsType' => '' ),
'FECHA_SCDP_SIIF' => array( 'totalsType' => '' ),
'USUARIO_SCDP_SIIF' => array( 'totalsType' => '' ),
'TIPO_SOL' => array( 'totalsType' => '' ),
'DEV_FECHA' => array( 'totalsType' => '' ),
'DEV_USER' => array( 'totalsType' => '' ),
'DEV_MSG' => array( 'totalsType' => '' ),
'DEV_MAIL' => array( 'totalsType' => '' ),
'VALOR_SOLICITADO' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'PAA_ID_FK',
'SOL_FECHA',
'SOL_DEPENDENCIA',
'OPERACION_ID_FK',
'USER_REG',
'SYS_STATUS',
'NUMERO_SCDP_SIIF',
'DOCUMENTO_SCDP_SIIF',
'FECHA_SCDP_SIIF',
'USUARIO_SCDP_SIIF',
'DEV_FECHA',
'DEV_USER',
'DEV_MSG',
'DEV_MAIL',
'VALOR_SOLICITADO',
'PAAU_ID' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array( 'USER_REG',
'VALOR_SOLICITADO',
'DEV_MAIL',
'DEV_MSG',
'DEV_USER',
'DEV_FECHA',
'USUARIO_SCDP_SIIF',
'FECHA_SCDP_SIIF',
'DOCUMENTO_SCDP_SIIF',
'NUMERO_SCDP_SIIF',
'SYS_STATUS',
'SOL_FECHA',
'SOL_DEPENDENCIA',
'PAA_ID_FK',
'OPERACION_ID_FK' ),
'filterFields' => array(  ),
'inlineAddFields' => array(  ),
'inlineEditFields' => array(  ),
'fieldItems' => array( 'PAA_ID_FK' => array( 'simple_grid_field1',
'simple_grid_field6' ),
'SOL_FECHA' => array( 'simple_grid_field2',
'simple_grid_field7' ),
'SOL_DEPENDENCIA' => array( 'simple_grid_field3',
'simple_grid_field8' ),
'OPERACION_ID_FK' => array( 'simple_grid_field4',
'simple_grid_field9' ),
'USER_REG' => array( 'simple_grid_field21',
'simple_grid_field23' ),
'SYS_STATUS' => array( 'simple_grid_field22',
'simple_grid_field24' ),
'NUMERO_SCDP_SIIF' => array( 'grid_field',
'grid_field_label' ),
'DOCUMENTO_SCDP_SIIF' => array( 'grid_field1',
'grid_field_label1' ),
'FECHA_SCDP_SIIF' => array( 'grid_field2',
'grid_field_label2' ),
'USUARIO_SCDP_SIIF' => array( 'grid_field3',
'grid_field_label3' ),
'DEV_FECHA' => array( 'grid_field4',
'grid_field_label4' ),
'DEV_USER' => array( 'grid_field5',
'grid_field_label5' ),
'DEV_MSG' => array( 'grid_field6',
'grid_field_label6' ),
'DEV_MAIL' => array( 'grid_field7',
'grid_field_label7' ),
'VALOR_SOLICITADO' => array( 'grid_field8',
'grid_field_label8' ),
'PAAU_ID' => array( 'grid_field9',
'grid_field_label9' ) ),
'hideEmptyFields' => array(  ) ),
'pageLinks' => array( 'edit' => true,
'add' => true,
'view' => true,
'print' => true ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'left' => array( 'logo1',
'expand_button',
'menu',
'search_panel' ),
'supertop' => array( 'collapse_button',
'breadcrumb',
'simple_search',
'list_options',
'loginform_login',
'username_button' ),
'above-grid' => array( 'add',
'inline_add',
'delete',
'details_found',
'page_size',
'print_panel' ),
'below-grid' => array( 'pagination' ),
'grid' => array( 'simple_grid_field6',
'simple_grid_field1',
'simple_grid_field7',
'simple_grid_field2',
'simple_grid_field8',
'simple_grid_field3',
'simple_grid_field9',
'simple_grid_field4',
'simple_grid_field23',
'simple_grid_field21',
'simple_grid_field24',
'simple_grid_field22',
'grid_edit',
'grid_inline_cancel',
'grid_view',
'custom_button',
'grid_checkbox_head',
'grid_checkbox',
'grid_field_label',
'grid_field',
'grid_field_label1',
'grid_field1',
'grid_field_label2',
'grid_field2',
'grid_field_label3',
'grid_field3',
'grid_field_label4',
'grid_field4',
'grid_field_label5',
'grid_field5',
'grid_field_label6',
'grid_field6',
'grid_field_label7',
'grid_field7',
'grid_field_label8',
'grid_field8',
'grid_field_label9',
'grid_field9' ),
'top' => array( 'master_info' ) ),
'formXtTags' => array( 'above-grid' => array( 'add_link',
'inlineadd_link',
'deleteselected_link',
'details_found',
'recsPerPage',
'print_friendly' ),
'below-grid' => array( 'pagination' ),
'top' => array( 'mastertable_block' ) ),
'itemForms' => array( 'logo1' => 'left',
'expand_button' => 'left',
'menu' => 'left',
'search_panel' => 'left',
'collapse_button' => 'supertop',
'breadcrumb' => 'supertop',
'simple_search' => 'supertop',
'list_options' => 'supertop',
'loginform_login' => 'supertop',
'username_button' => 'supertop',
'add' => 'above-grid',
'inline_add' => 'above-grid',
'delete' => 'above-grid',
'details_found' => 'above-grid',
'page_size' => 'above-grid',
'print_panel' => 'above-grid',
'pagination' => 'below-grid',
'simple_grid_field6' => 'grid',
'simple_grid_field1' => 'grid',
'simple_grid_field7' => 'grid',
'simple_grid_field2' => 'grid',
'simple_grid_field8' => 'grid',
'simple_grid_field3' => 'grid',
'simple_grid_field9' => 'grid',
'simple_grid_field4' => 'grid',
'simple_grid_field23' => 'grid',
'simple_grid_field21' => 'grid',
'simple_grid_field24' => 'grid',
'simple_grid_field22' => 'grid',
'grid_edit' => 'grid',
'grid_inline_cancel' => 'grid',
'grid_view' => 'grid',
'custom_button' => 'grid',
'grid_checkbox_head' => 'grid',
'grid_checkbox' => 'grid',
'grid_field_label' => 'grid',
'grid_field' => 'grid',
'grid_field_label1' => 'grid',
'grid_field1' => 'grid',
'grid_field_label2' => 'grid',
'grid_field2' => 'grid',
'grid_field_label3' => 'grid',
'grid_field3' => 'grid',
'grid_field_label4' => 'grid',
'grid_field4' => 'grid',
'grid_field_label5' => 'grid',
'grid_field5' => 'grid',
'grid_field_label6' => 'grid',
'grid_field6' => 'grid',
'grid_field_label7' => 'grid',
'grid_field7' => 'grid',
'grid_field_label8' => 'grid',
'grid_field8' => 'grid',
'grid_field_label9' => 'grid',
'grid_field9' => 'grid',
'master_info' => 'top' ),
'itemLocations' => array( 'simple_grid_field6' => array( 'location' => 'grid',
'cellId' => 'headcell_field1' ),
'simple_grid_field1' => array( 'location' => 'grid',
'cellId' => 'cell_field1' ),
'simple_grid_field7' => array( 'location' => 'grid',
'cellId' => 'headcell_field2' ),
'simple_grid_field2' => array( 'location' => 'grid',
'cellId' => 'cell_field2' ),
'simple_grid_field8' => array( 'location' => 'grid',
'cellId' => 'headcell_field3' ),
'simple_grid_field3' => array( 'location' => 'grid',
'cellId' => 'cell_field3' ),
'simple_grid_field9' => array( 'location' => 'grid',
'cellId' => 'headcell_field4' ),
'simple_grid_field4' => array( 'location' => 'grid',
'cellId' => 'cell_field4' ),
'simple_grid_field23' => array( 'location' => 'grid',
'cellId' => 'headcell_field5' ),
'simple_grid_field21' => array( 'location' => 'grid',
'cellId' => 'cell_field5' ),
'simple_grid_field24' => array( 'location' => 'grid',
'cellId' => 'headcell_field6' ),
'simple_grid_field22' => array( 'location' => 'grid',
'cellId' => 'cell_field6' ),
'grid_edit' => array( 'location' => 'grid',
'cellId' => 'cell_icons' ),
'grid_inline_cancel' => array( 'location' => 'grid',
'cellId' => 'cell_icons' ),
'grid_view' => array( 'location' => 'grid',
'cellId' => 'cell_icons' ),
'custom_button' => array( 'location' => 'grid',
'cellId' => 'cell_icons' ),
'grid_checkbox_head' => array( 'location' => 'grid',
'cellId' => 'headcell_checkbox' ),
'grid_checkbox' => array( 'location' => 'grid',
'cellId' => 'cell_checkbox' ),
'grid_field_label' => array( 'location' => 'grid',
'cellId' => 'headcell_field7' ),
'grid_field' => array( 'location' => 'grid',
'cellId' => 'cell_field7' ),
'grid_field_label1' => array( 'location' => 'grid',
'cellId' => 'headcell_field8' ),
'grid_field1' => array( 'location' => 'grid',
'cellId' => 'cell_field8' ),
'grid_field_label2' => array( 'location' => 'grid',
'cellId' => 'headcell_field9' ),
'grid_field2' => array( 'location' => 'grid',
'cellId' => 'cell_field9' ),
'grid_field_label3' => array( 'location' => 'grid',
'cellId' => 'headcell_field10' ),
'grid_field3' => array( 'location' => 'grid',
'cellId' => 'cell_field10' ),
'grid_field_label4' => array( 'location' => 'grid',
'cellId' => 'headcell_field' ),
'grid_field4' => array( 'location' => 'grid',
'cellId' => 'cell_field' ),
'grid_field_label5' => array( 'location' => 'grid',
'cellId' => 'headcell_field11' ),
'grid_field5' => array( 'location' => 'grid',
'cellId' => 'cell_field11' ),
'grid_field_label6' => array( 'location' => 'grid',
'cellId' => 'headcell_field12' ),
'grid_field6' => array( 'location' => 'grid',
'cellId' => 'cell_field12' ),
'grid_field_label7' => array( 'location' => 'grid',
'cellId' => 'headcell_field13' ),
'grid_field7' => array( 'location' => 'grid',
'cellId' => 'cell_field13' ),
'grid_field_label8' => array( 'location' => 'grid',
'cellId' => 'headcell_field15' ),
'grid_field8' => array( 'location' => 'grid',
'cellId' => 'headcell_field16' ),
'grid_field_label9' => array( 'location' => 'grid',
'cellId' => 'headcell_field14' ),
'grid_field9' => array( 'location' => 'grid',
'cellId' => 'cell_field14' ) ),
'itemVisiblity' => array( 'expand_button' => 5,
'menu' => 3,
'search_panel' => 5,
'collapse_button' => 5,
'simple_search' => 3,
'list_options' => 3,
'loginform_login' => 3,
'username_button' => 3,
'print_panel' => 5 ) ),
'itemsByType' => array( 'page_size' => array( 'page_size' ),
'details_found' => array( 'details_found' ),
'breadcrumb' => array( 'breadcrumb' ),
'menu' => array( 'menu' ),
'simple_search' => array( 'simple_search' ),
'pagination' => array( 'pagination' ),
'search_panel' => array( 'search_panel' ),
'list_options' => array( 'list_options' ),
'show_search_panel' => array( 'show_search_panel' ),
'hide_search_panel' => array( 'hide_search_panel' ),
'search_panel_field' => array( 'search_panel_field5',
'search_panel_field7',
'search_panel_field16',
'search_panel_field17',
'search_panel_field19',
'search_panel_field22',
'search_panel_field',
'search_panel_field1',
'search_panel_field2',
'search_panel_field3',
'search_panel_field4',
'search_panel_field6',
'search_panel_field8',
'search_panel_field9',
'search_panel_field10' ),
'username_button' => array( 'username_button' ),
'loginform_login' => array( 'loginform_login' ),
'logout_link' => array( 'logout_link' ),
'adminarea_link' => array( 'adminarea_link' ),
'collapse_button' => array( 'collapse_button' ),
'add' => array( 'add' ),
'grid_edit' => array( 'grid_edit' ),
'grid_view' => array( 'grid_view' ),
'print_panel' => array( 'print_panel' ),
'print_scope' => array( 'print_scope' ),
'print_button' => array( 'print_button' ),
'print_records' => array( 'print_records' ),
'grid_checkbox' => array( 'grid_checkbox' ),
'grid_checkbox_head' => array( 'grid_checkbox_head' ),
'export' => array( 'export' ),
'-' => array( '-',
'-1',
'-2',
'-3' ),
'export_selected' => array( 'export_selected' ),
'import' => array( 'import' ),
'delete' => array( 'delete' ),
'delete_selected' => array( 'delete_selected' ),
'advsearch_link' => array( 'advsearch_link' ),
'grid_field' => array( 'simple_grid_field1',
'simple_grid_field2',
'simple_grid_field3',
'simple_grid_field4',
'simple_grid_field21',
'simple_grid_field22',
'grid_field',
'grid_field1',
'grid_field2',
'grid_field3',
'grid_field4',
'grid_field5',
'grid_field6',
'grid_field7',
'grid_field8',
'grid_field9' ),
'master_info' => array( 'master_info' ),
'logo' => array( 'logo1' ),
'grid_field_label' => array( 'simple_grid_field6',
'simple_grid_field7',
'simple_grid_field8',
'simple_grid_field9',
'simple_grid_field23',
'simple_grid_field24',
'grid_field_label',
'grid_field_label1',
'grid_field_label2',
'grid_field_label3',
'grid_field_label4',
'grid_field_label5',
'grid_field_label6',
'grid_field_label7',
'grid_field_label8',
'grid_field_label9' ),
'custom_button' => array( 'custom_button' ),
'expand_button' => array( 'expand_button' ),
'inline_add' => array( 'inline_add' ),
'grid_inline_cancel' => array( 'grid_inline_cancel' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'headcell_icons' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_checkbox' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array( 'checkbox_column' ),
'items' => array( 'grid_checkbox_head' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field1' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array( 'PAA_ID_FK_fieldheadercolumn' ),
'items' => array( 'simple_grid_field6' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field2' => array( 'cols' => array( 3 ),
'rows' => array( 0 ),
'tags' => array( 'SOL_FECHA_fieldheadercolumn' ),
'items' => array( 'simple_grid_field7' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field3' => array( 'cols' => array( 4 ),
'rows' => array( 0 ),
'tags' => array( 'SOL_DEPENDENCIA_fieldheadercolumn' ),
'items' => array( 'simple_grid_field8' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field4' => array( 'cols' => array( 5 ),
'rows' => array( 0 ),
'tags' => array( 'OPERACION_ID_FK_fieldheadercolumn' ),
'items' => array( 'simple_grid_field9' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field15' => array( 'cols' => array( 6 ),
'rows' => array( 0 ),
'tags' => array( 'VALOR_SOLICITADO_fieldheadercolumn' ),
'items' => array( 'grid_field_label8' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field5' => array( 'cols' => array( 7 ),
'rows' => array( 0 ),
'tags' => array( 'USER_REG_fieldheadercolumn' ),
'items' => array( 'simple_grid_field23' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field6' => array( 'cols' => array( 8 ),
'rows' => array( 0 ),
'tags' => array( 'SYS_STATUS_fieldheadercolumn' ),
'items' => array( 'simple_grid_field24' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field7' => array( 'cols' => array( 9 ),
'rows' => array( 0 ),
'tags' => array( 'NUMERO_SCDP_SIIF_fieldheadercolumn' ),
'items' => array( 'grid_field_label' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field8' => array( 'cols' => array( 10 ),
'rows' => array( 0 ),
'tags' => array( 'DOCUMENTO_SCDP_SIIF_fieldheadercolumn' ),
'items' => array( 'grid_field_label1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field9' => array( 'cols' => array( 11 ),
'rows' => array( 0 ),
'tags' => array( 'FECHA_SCDP_SIIF_fieldheadercolumn' ),
'items' => array( 'grid_field_label2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field10' => array( 'cols' => array( 12 ),
'rows' => array( 0 ),
'tags' => array( 'USUARIO_SCDP_SIIF_fieldheadercolumn' ),
'items' => array( 'grid_field_label3' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field' => array( 'cols' => array( 13 ),
'rows' => array( 0 ),
'tags' => array( 'DEV_FECHA_fieldheadercolumn' ),
'items' => array( 'grid_field_label4' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field11' => array( 'cols' => array( 14 ),
'rows' => array( 0 ),
'tags' => array( 'DEV_USER_fieldheadercolumn' ),
'items' => array( 'grid_field_label5' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field12' => array( 'cols' => array( 15 ),
'rows' => array( 0 ),
'tags' => array( 'DEV_MSG_fieldheadercolumn' ),
'items' => array( 'grid_field_label6' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field13' => array( 'cols' => array( 16 ),
'rows' => array( 0 ),
'tags' => array( 'DEV_MAIL_fieldheadercolumn' ),
'items' => array( 'grid_field_label7' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field14' => array( 'cols' => array( 17 ),
'rows' => array( 0 ),
'tags' => array( 'PAAU_ID_fieldheadercolumn' ),
'items' => array( 'grid_field_label9' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_icons' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => true,
'fixedAtClient' => true ),
'cell_checkbox' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array( 'checkbox_column' ),
'items' => array( 'grid_checkbox' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field1' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array( 'PAA_ID_FK_fieldcolumn' ),
'items' => array( 'simple_grid_field1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field2' => array( 'cols' => array( 3 ),
'rows' => array( 1 ),
'tags' => array( 'SOL_FECHA_fieldcolumn' ),
'items' => array( 'simple_grid_field2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field3' => array( 'cols' => array( 4 ),
'rows' => array( 1 ),
'tags' => array( 'SOL_DEPENDENCIA_fieldcolumn' ),
'items' => array( 'simple_grid_field3' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field4' => array( 'cols' => array( 5 ),
'rows' => array( 1 ),
'tags' => array( 'OPERACION_ID_FK_fieldcolumn' ),
'items' => array( 'simple_grid_field4' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field16' => array( 'cols' => array( 6 ),
'rows' => array( 1 ),
'tags' => array( 'VALOR_SOLICITADO_fieldcolumn' ),
'items' => array( 'grid_field8' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field5' => array( 'cols' => array( 7 ),
'rows' => array( 1 ),
'tags' => array( 'USER_REG_fieldcolumn' ),
'items' => array( 'simple_grid_field21' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field6' => array( 'cols' => array( 8 ),
'rows' => array( 1 ),
'tags' => array( 'SYS_STATUS_fieldcolumn' ),
'items' => array( 'simple_grid_field22' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field7' => array( 'cols' => array( 9 ),
'rows' => array( 1 ),
'tags' => array( 'NUMERO_SCDP_SIIF_fieldcolumn' ),
'items' => array( 'grid_field' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field8' => array( 'cols' => array( 10 ),
'rows' => array( 1 ),
'tags' => array( 'DOCUMENTO_SCDP_SIIF_fieldcolumn' ),
'items' => array( 'grid_field1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field9' => array( 'cols' => array( 11 ),
'rows' => array( 1 ),
'tags' => array( 'FECHA_SCDP_SIIF_fieldcolumn' ),
'items' => array( 'grid_field2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field10' => array( 'cols' => array( 12 ),
'rows' => array( 1 ),
'tags' => array( 'USUARIO_SCDP_SIIF_fieldcolumn' ),
'items' => array( 'grid_field3' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field' => array( 'cols' => array( 13 ),
'rows' => array( 1 ),
'tags' => array( 'DEV_FECHA_fieldcolumn' ),
'items' => array( 'grid_field4' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field11' => array( 'cols' => array( 14 ),
'rows' => array( 1 ),
'tags' => array( 'DEV_USER_fieldcolumn' ),
'items' => array( 'grid_field5' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field12' => array( 'cols' => array( 15 ),
'rows' => array( 1 ),
'tags' => array( 'DEV_MSG_fieldcolumn' ),
'items' => array( 'grid_field6' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field13' => array( 'cols' => array( 16 ),
'rows' => array( 1 ),
'tags' => array( 'DEV_MAIL_fieldcolumn' ),
'items' => array( 'grid_field7' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field14' => array( 'cols' => array( 17 ),
'rows' => array( 1 ),
'tags' => array( 'PAAU_ID_fieldcolumn' ),
'items' => array( 'grid_field9' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_icons' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_checkbox' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field1' => array( 'cols' => array( 2 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field2' => array( 'cols' => array( 3 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field3' => array( 'cols' => array( 4 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field4' => array( 'cols' => array( 5 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field17' => array( 'cols' => array( 6 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field5' => array( 'cols' => array( 7 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field6' => array( 'cols' => array( 8 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field7' => array( 'cols' => array( 9 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field8' => array( 'cols' => array( 10 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field9' => array( 'cols' => array( 11 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field10' => array( 'cols' => array( 12 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field' => array( 'cols' => array( 13 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field11' => array( 'cols' => array( 14 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field12' => array( 'cols' => array( 15 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field13' => array( 'cols' => array( 16 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field14' => array( 'cols' => array( 17 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 18,
'height' => 3 ) ) ),
'loginForm' => array( 'loginForm' => 0 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array( 'details_found' => array( 'tag' => 'DISPLAYING',
'type' => 2 ) ) ),
'gridType' => 0,
'recsPerRow' => 1,
'hasCustomButtons' => true,
'customButtons' => array( 'gen_scdp' ) ),
'misc' => array( 'type' => 'list',
'breadcrumb' => true ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array( 'gen_scdp' ) ),
'dataGrid' => array( 'groupFields' => array(  ) ) );
			$pageArray = array( 'id' => 'list',
'type' => 'list',
'layoutId' => 'leftbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'left' => array( 'modelId' => 'leftbar-menu',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c0' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c0' => array( 'model' => 'c0',
'items' => array( 'logo1',
'expand_button' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c1' => array( 'model' => 'c1',
'items' => array( 'menu',
'search_panel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'supertop' => array( 'modelId' => 'leftbar-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'collapse_button',
'breadcrumb' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'simple_search',
'list_options',
'loginform_login',
'username_button' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'list-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'add',
'inline_add',
'delete' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'details_found',
'page_size',
'print_panel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'list-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'pagination' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'horizontal-grid',
'grid' => array( array( 'section' => 'head',
'cells' => array( array( 'cell' => 'headcell_icons' ),
array( 'cell' => 'headcell_checkbox' ),
array( 'cell' => 'headcell_field1' ),
array( 'cell' => 'headcell_field2' ),
array( 'cell' => 'headcell_field3' ),
array( 'cell' => 'headcell_field4' ),
array( 'cell' => 'headcell_field15' ),
array( 'cell' => 'headcell_field5' ),
array( 'cell' => 'headcell_field6' ),
array( 'cell' => 'headcell_field7' ),
array( 'cell' => 'headcell_field8' ),
array( 'cell' => 'headcell_field9' ),
array( 'cell' => 'headcell_field10' ),
array( 'cell' => 'headcell_field' ),
array( 'cell' => 'headcell_field11' ),
array( 'cell' => 'headcell_field12' ),
array( 'cell' => 'headcell_field13' ),
array( 'cell' => 'headcell_field14' ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_icons' ),
array( 'cell' => 'cell_checkbox' ),
array( 'cell' => 'cell_field1' ),
array( 'cell' => 'cell_field2' ),
array( 'cell' => 'cell_field3' ),
array( 'cell' => 'cell_field4' ),
array( 'cell' => 'headcell_field16' ),
array( 'cell' => 'cell_field5' ),
array( 'cell' => 'cell_field6' ),
array( 'cell' => 'cell_field7' ),
array( 'cell' => 'cell_field8' ),
array( 'cell' => 'cell_field9' ),
array( 'cell' => 'cell_field10' ),
array( 'cell' => 'cell_field' ),
array( 'cell' => 'cell_field11' ),
array( 'cell' => 'cell_field12' ),
array( 'cell' => 'cell_field13' ),
array( 'cell' => 'cell_field14' ) ) ),
array( 'section' => 'foot',
'cells' => array( array( 'cell' => 'footcell_icons' ),
array( 'cell' => 'footcell_checkbox' ),
array( 'cell' => 'footcell_field1' ),
array( 'cell' => 'footcell_field2' ),
array( 'cell' => 'footcell_field3' ),
array( 'cell' => 'footcell_field4' ),
array( 'cell' => 'headcell_field17' ),
array( 'cell' => 'footcell_field5' ),
array( 'cell' => 'footcell_field6' ),
array( 'cell' => 'footcell_field7' ),
array( 'cell' => 'footcell_field8' ),
array( 'cell' => 'footcell_field9' ),
array( 'cell' => 'footcell_field10' ),
array( 'cell' => 'footcell_field' ),
array( 'cell' => 'footcell_field11' ),
array( 'cell' => 'footcell_field12' ),
array( 'cell' => 'footcell_field13' ),
array( 'cell' => 'footcell_field14' ) ) ) ),
'cells' => array( 'headcell_field1' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field6' ),
'field' => 'PAA_ID_FK',
'columnName' => 'field' ),
'cell_field1' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field1' ),
'field' => 'PAA_ID_FK',
'columnName' => 'field' ),
'footcell_field1' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field2' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field7' ),
'field' => 'SOL_FECHA',
'columnName' => 'field' ),
'cell_field2' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field2' ),
'field' => 'SOL_FECHA',
'columnName' => 'field' ),
'footcell_field2' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field3' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field8' ),
'field' => 'SOL_DEPENDENCIA',
'columnName' => 'field' ),
'cell_field3' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field3' ),
'field' => 'SOL_DEPENDENCIA',
'columnName' => 'field' ),
'footcell_field3' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field4' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field9' ),
'field' => 'OPERACION_ID_FK',
'columnName' => 'field' ),
'cell_field4' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field4' ),
'field' => 'OPERACION_ID_FK',
'columnName' => 'field' ),
'footcell_field4' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field5' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field23' ),
'field' => 'USER_REG',
'columnName' => 'field' ),
'cell_field5' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field21' ),
'field' => 'USER_REG',
'columnName' => 'field' ),
'footcell_field5' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field6' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field24' ),
'field' => 'SYS_STATUS',
'columnName' => 'field' ),
'cell_field6' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field22' ),
'field' => 'SYS_STATUS',
'columnName' => 'field' ),
'footcell_field6' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_icons' => array( 'model' => 'headcell_icons',
'items' => array(  ),
'columnName' => 'list-icons' ),
'cell_icons' => array( 'model' => 'cell_icons',
'items' => array( 'grid_edit',
'grid_inline_cancel',
'grid_view',
'custom_button' ),
'columnName' => 'list-icons' ),
'footcell_icons' => array( 'model' => 'footcell_icons',
'items' => array(  ),
'columnName' => 'list-icons' ),
'headcell_checkbox' => array( 'model' => 'headcell_checkbox',
'items' => array( 'grid_checkbox_head' ),
'columnName' => 'checkbox' ),
'cell_checkbox' => array( 'model' => 'cell_checkbox',
'items' => array( 'grid_checkbox' ),
'columnName' => 'checkbox' ),
'footcell_checkbox' => array( 'model' => 'footcell_checkbox',
'items' => array(  ),
'columnName' => 'checkbox' ),
'headcell_field7' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label' ),
'field' => 'NUMERO_SCDP_SIIF',
'columnName' => 'field' ),
'cell_field7' => array( 'model' => 'cell_field',
'items' => array( 'grid_field' ),
'field' => 'NUMERO_SCDP_SIIF',
'columnName' => 'field' ),
'footcell_field7' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field8' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label1' ),
'field' => 'DOCUMENTO_SCDP_SIIF',
'columnName' => 'field' ),
'cell_field8' => array( 'model' => 'cell_field',
'items' => array( 'grid_field1' ),
'field' => 'DOCUMENTO_SCDP_SIIF',
'columnName' => 'field' ),
'footcell_field8' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field9' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label2' ),
'field' => 'FECHA_SCDP_SIIF',
'columnName' => 'field' ),
'cell_field9' => array( 'model' => 'cell_field',
'items' => array( 'grid_field2' ),
'field' => 'FECHA_SCDP_SIIF',
'columnName' => 'field' ),
'footcell_field9' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field10' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label3' ),
'field' => 'USUARIO_SCDP_SIIF',
'columnName' => 'field' ),
'cell_field10' => array( 'model' => 'cell_field',
'items' => array( 'grid_field3' ),
'field' => 'USUARIO_SCDP_SIIF',
'columnName' => 'field' ),
'footcell_field10' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label4' ),
'field' => 'DEV_FECHA',
'columnName' => 'field' ),
'cell_field' => array( 'model' => 'cell_field',
'items' => array( 'grid_field4' ),
'field' => 'DEV_FECHA',
'columnName' => 'field' ),
'footcell_field' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field11' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label5' ),
'field' => 'DEV_USER',
'columnName' => 'field' ),
'cell_field11' => array( 'model' => 'cell_field',
'items' => array( 'grid_field5' ),
'field' => 'DEV_USER',
'columnName' => 'field' ),
'footcell_field11' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field12' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label6' ),
'field' => 'DEV_MSG',
'columnName' => 'field' ),
'cell_field12' => array( 'model' => 'cell_field',
'items' => array( 'grid_field6' ),
'field' => 'DEV_MSG',
'columnName' => 'field' ),
'footcell_field12' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field13' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label7' ),
'field' => 'DEV_MAIL',
'columnName' => 'field' ),
'cell_field13' => array( 'model' => 'cell_field',
'items' => array( 'grid_field7' ),
'field' => 'DEV_MAIL',
'columnName' => 'field' ),
'footcell_field13' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field15' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label8' ),
'columnName' => 'field',
'field' => 'VALOR_SOLICITADO' ),
'headcell_field16' => array( 'model' => 'cell_field',
'items' => array( 'grid_field8' ),
'columnName' => 'field',
'field' => 'VALOR_SOLICITADO' ),
'headcell_field17' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field14' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field_label9' ),
'field' => 'PAAU_ID',
'columnName' => 'field' ),
'cell_field14' => array( 'model' => 'cell_field',
'items' => array( 'grid_field9' ),
'field' => 'PAAU_ID',
'columnName' => 'field' ),
'footcell_field14' => array( 'model' => 'footcell_field',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'list-sidebar-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c2' => array( 'model' => 'c2',
'items' => array( 'master_info' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'page_size' => array( 'type' => 'page_size' ),
'details_found' => array( 'type' => 'details_found' ),
'breadcrumb' => array( 'type' => 'breadcrumb' ),
'menu' => array( 'type' => 'menu' ),
'simple_search' => array( 'type' => 'simple_search' ),
'pagination' => array( 'type' => 'pagination' ),
'search_panel' => array( 'type' => 'search_panel',
'items' => array( 'search_panel_field22',
'search_panel_field10',
'search_panel_field9',
'search_panel_field8',
'search_panel_field6',
'search_panel_field4',
'search_panel_field3',
'search_panel_field2',
'search_panel_field1',
'search_panel_field',
'search_panel_field19',
'search_panel_field17',
'search_panel_field16',
'search_panel_field7',
'search_panel_field5' ),
'_flexiblePanel' => true ),
'list_options' => array( 'type' => 'list_options',
'items' => array( 'export_selected',
'delete_selected',
'-3',
'advsearch_link',
'show_search_panel',
'hide_search_panel',
'-1',
'export',
'-2',
'import' ) ),
'show_search_panel' => array( 'type' => 'show_search_panel' ),
'hide_search_panel' => array( 'type' => 'hide_search_panel' ),
'search_panel_field5' => array( 'field' => 'OPERACION_ID_FK',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field7' => array( 'field' => 'PAA_ID_FK',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => true ),
'search_panel_field16' => array( 'field' => 'SOL_DEPENDENCIA',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => true ),
'search_panel_field17' => array( 'field' => 'SOL_FECHA',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field19' => array( 'field' => 'SYS_STATUS',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field22' => array( 'field' => 'USER_REG',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => true ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'logout_link',
'adminarea_link' ) ),
'loginform_login' => array( 'type' => 'loginform_login',
'popup' => false ),
'logout_link' => array( 'type' => 'logout_link' ),
'adminarea_link' => array( 'type' => 'adminarea_link' ),
'collapse_button' => array( 'type' => 'collapse_button' ),
'add' => array( 'type' => 'add',
'popup' => false ),
'grid_edit' => array( 'type' => 'grid_edit',
'buttonStyle' => 'default',
'buttonSize' => 'normal',
'popup' => true ),
'grid_view' => array( 'type' => 'grid_view',
'buttonStyle' => 'default',
'buttonSize' => 'normal',
'popup' => true ),
'print_panel' => array( 'type' => 'print_panel',
'items' => array( 'print_scope',
'print_records',
'print_button' ) ),
'print_scope' => array( 'type' => 'print_scope' ),
'print_button' => array( 'type' => 'print_button' ),
'print_records' => array( 'type' => 'print_records' ),
'grid_checkbox' => array( 'type' => 'grid_checkbox' ),
'grid_checkbox_head' => array( 'type' => 'grid_checkbox_head' ),
'export' => array( 'type' => 'export' ),
'-' => array( 'type' => '-' ),
'export_selected' => array( 'type' => 'export_selected' ),
'-1' => array( 'type' => '-' ),
'import' => array( 'type' => 'import' ),
'-2' => array( 'type' => '-' ),
'delete' => array( 'type' => 'delete' ),
'delete_selected' => array( 'type' => 'delete_selected' ),
'advsearch_link' => array( 'type' => 'advsearch_link' ),
'-3' => array( 'type' => '-' ),
'simple_grid_field1' => array( 'field' => 'PAA_ID_FK',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field2' => array( 'field' => 'SOL_FECHA',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field3' => array( 'field' => 'SOL_DEPENDENCIA',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field4' => array( 'field' => 'OPERACION_ID_FK',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field21' => array( 'field' => 'USER_REG',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field22' => array( 'field' => 'SYS_STATUS',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'master_info' => array( 'type' => 'master_info',
'tables' => array( 'global_operacion' => 'true' ) ),
'logo1' => array( 'type' => 'logo' ),
'simple_grid_field6' => array( 'type' => 'grid_field_label',
'field' => 'PAA_ID_FK',
'clickSort' => true ),
'simple_grid_field7' => array( 'type' => 'grid_field_label',
'field' => 'SOL_FECHA',
'clickSort' => true ),
'simple_grid_field8' => array( 'type' => 'grid_field_label',
'field' => 'SOL_DEPENDENCIA',
'clickSort' => true ),
'simple_grid_field9' => array( 'type' => 'grid_field_label',
'field' => 'OPERACION_ID_FK',
'clickSort' => true ),
'simple_grid_field23' => array( 'type' => 'grid_field_label',
'field' => 'USER_REG',
'clickSort' => true ),
'simple_grid_field24' => array( 'type' => 'grid_field_label',
'field' => 'SYS_STATUS',
'clickSort' => true ),
'custom_button' => array( 'eventId' => 'gen_scdp',
'label' => array( 'text' => '',
'type' => 0 ),
'type' => 'custom_button',
'icon' => array( 'fa' => 'file-pdf-o' ),
'buttonStyle' => 'success',
'buttonSize' => 'normal' ),
'grid_field' => array( 'field' => 'NUMERO_SCDP_SIIF',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'grid_field_label' => array( 'type' => 'grid_field_label',
'field' => 'NUMERO_SCDP_SIIF',
'clickSort' => true ),
'search_panel_field' => array( 'field' => 'NUMERO_SCDP_SIIF',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'grid_field1' => array( 'field' => 'DOCUMENTO_SCDP_SIIF',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'grid_field_label1' => array( 'type' => 'grid_field_label',
'field' => 'DOCUMENTO_SCDP_SIIF',
'clickSort' => true ),
'search_panel_field1' => array( 'field' => 'DOCUMENTO_SCDP_SIIF',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'grid_field2' => array( 'field' => 'FECHA_SCDP_SIIF',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'grid_field_label2' => array( 'type' => 'grid_field_label',
'field' => 'FECHA_SCDP_SIIF',
'clickSort' => true ),
'search_panel_field2' => array( 'field' => 'FECHA_SCDP_SIIF',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'grid_field3' => array( 'field' => 'USUARIO_SCDP_SIIF',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'grid_field_label3' => array( 'type' => 'grid_field_label',
'field' => 'USUARIO_SCDP_SIIF',
'clickSort' => true ),
'search_panel_field3' => array( 'field' => 'USUARIO_SCDP_SIIF',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field4' => array( 'field' => 'DEV_FECHA',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'grid_field4' => array( 'field' => 'DEV_FECHA',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'grid_field_label4' => array( 'type' => 'grid_field_label',
'field' => 'DEV_FECHA' ),
'grid_field5' => array( 'field' => 'DEV_USER',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'grid_field_label5' => array( 'type' => 'grid_field_label',
'field' => 'DEV_USER' ),
'search_panel_field6' => array( 'field' => 'DEV_USER',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'grid_field6' => array( 'field' => 'DEV_MSG',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'grid_field_label6' => array( 'type' => 'grid_field_label',
'field' => 'DEV_MSG' ),
'search_panel_field8' => array( 'field' => 'DEV_MSG',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'grid_field7' => array( 'field' => 'DEV_MAIL',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'grid_field_label7' => array( 'type' => 'grid_field_label',
'field' => 'DEV_MAIL' ),
'search_panel_field9' => array( 'field' => 'DEV_MAIL',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'grid_field8' => array( 'field' => 'VALOR_SOLICITADO',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'grid_field_label8' => array( 'type' => 'grid_field_label',
'field' => 'VALOR_SOLICITADO' ),
'search_panel_field10' => array( 'field' => 'VALOR_SOLICITADO',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'grid_field9' => array( 'field' => 'PAAU_ID',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'grid_field_label9' => array( 'type' => 'grid_field_label',
'field' => 'PAAU_ID' ),
'expand_button' => array( 'type' => 'expand_button' ),
'inline_add' => array( 'type' => 'inline_add',
'detailsOnly' => true ),
'grid_inline_cancel' => array( 'type' => 'grid_inline_cancel' ) ),
'dbProps' => array(  ),
'version' => 4 );
		?>