<?php
			$optionsArray = array( 'totals' => array( 'PAA_ID' => array( 'totalsType' => '' ),
'COD_UNSPSC' => array( 'totalsType' => '' ),
'DESCRIPCION' => array( 'totalsType' => '' ),
'MES_INICIO' => array( 'totalsType' => '' ),
'MES_PRESENTA' => array( 'totalsType' => '' ),
'DURACION_CONTRATO' => array( 'totalsType' => '' ),
'DURACION_ESTIMADA_DMA' => array( 'totalsType' => '' ),
'MODALIDAD' => array( 'totalsType' => '' ),
'FUENTE_RECURSOS' => array( 'totalsType' => '' ),
'VALOR' => array( 'totalsType' => '' ),
'USOS_TOTAL' => array( 'totalsType' => '' ),
'VALOR_VIGENCIA' => array( 'totalsType' => '' ),
'VF' => array( 'totalsType' => '' ),
'ESTADO_VF' => array( 'totalsType' => '' ),
'UNIDAD_CONTRATACION' => array( 'totalsType' => '' ),
'COD_UBICACION' => array( 'totalsType' => '' ),
'RESPONSABLE_NOMBRE' => array( 'totalsType' => '' ),
'RESPONSABLE_TELEFONO' => array( 'totalsType' => '' ),
'RESPONSABLE_EMAIL' => array( 'totalsType' => '' ),
'responsable' => array( 'totalsType' => '' ),
'vigencia' => array( 'totalsType' => '' ),
'sys_user' => array( 'totalsType' => '' ),
'sys_date' => array( 'totalsType' => '' ),
'sys_status' => array( 'totalsType' => '' ),
'TIPOSOL' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'PAA_ID',
'DESCRIPCION',
'FUENTE_RECURSOS',
'VALOR',
'COD_UBICACION',
'responsable',
'vigencia',
'sys_user',
'sys_status',
'TIPOSOL',
'USOS_TOTAL' ),
'exportFields' => array( 'PAA_ID',
'DESCRIPCION',
'FUENTE_RECURSOS',
'VALOR',
'COD_UBICACION',
'responsable',
'vigencia',
'sys_user',
'sys_status',
'TIPOSOL',
'USOS_TOTAL' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'PAA_ID' => array( 'export_field' ),
'DESCRIPCION' => array( 'export_field2' ),
'FUENTE_RECURSOS' => array( 'export_field9' ),
'VALOR' => array( 'export_field10' ),
'COD_UBICACION' => array( 'export_field15' ),
'responsable' => array( 'export_field19' ),
'vigencia' => array( 'export_field20' ),
'sys_user' => array( 'export_field21' ),
'sys_status' => array( 'export_field23' ),
'TIPOSOL' => array( 'export_field1' ),
'USOS_TOTAL' => array( 'export_field3' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array( 'export_field',
'export_field2',
'export_field9',
'export_field10',
'export_field15',
'export_field19',
'export_field20',
'export_field21',
'export_field23',
'export_field1',
'export_field3' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_field' => 'grid',
'export_field2' => 'grid',
'export_field9' => 'grid',
'export_field10' => 'grid',
'export_field15' => 'grid',
'export_field19' => 'grid',
'export_field20' => 'grid',
'export_field21' => 'grid',
'export_field23' => 'grid',
'export_field1' => 'grid',
'export_field3' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field',
'export_field2',
'export_field9',
'export_field10',
'export_field15',
'export_field19',
'export_field20',
'export_field21',
'export_field23',
'export_field1',
'export_field3' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ) ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => true,
'csv' => true,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field',
'export_field2',
'export_field9',
'export_field10',
'export_field15',
'export_field19',
'export_field20',
'export_field21',
'export_field23',
'export_field1',
'export_field3' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field' => array( 'field' => 'PAA_ID',
'type' => 'export_field' ),
'export_field2' => array( 'field' => 'DESCRIPCION',
'type' => 'export_field' ),
'export_field9' => array( 'field' => 'FUENTE_RECURSOS',
'type' => 'export_field' ),
'export_field10' => array( 'field' => 'VALOR',
'type' => 'export_field' ),
'export_field15' => array( 'field' => 'COD_UBICACION',
'type' => 'export_field' ),
'export_field19' => array( 'field' => 'responsable',
'type' => 'export_field' ),
'export_field20' => array( 'field' => 'vigencia',
'type' => 'export_field' ),
'export_field21' => array( 'field' => 'sys_user',
'type' => 'export_field' ),
'export_field23' => array( 'field' => 'sys_status',
'type' => 'export_field' ),
'export_field1' => array( 'field' => 'TIPOSOL',
'type' => 'export_field' ),
'export_field3' => array( 'field' => 'USOS_TOTAL',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 4,
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>