<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */
 
 class eventclass_paa_master  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["BeforeMoveNextList"]=true;

		$this->events["AfterAdd"]=true;





	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// List page: After record processed
function BeforeMoveNextList(&$data, &$row, &$record, $recordId, &$pageObject)
{

		$sql = DB::prepareSQL("UPDATE
mincit_global.paa_master
INNER JOIN mincit_global.q_paa_total_usos ON mincit_global.paa_master.PAA_ID = mincit_global.q_paa_total_usos.PAA_ID_FK
SET
mincit_global.paa_master.USOS_TOTAL = mincit_global.q_paa_total_usos.TOTAL_USOS;");
DB::Exec( $sql );

$sql = DB::prepareSQL("UPDATE
mincit_global.paa_master
INNER JOIN edl.usuario ON mincit_global.paa_master.responsable = edl.usuario.usuario
INNER JOIN edl.funcionario ON edl.usuario.idFuncionario = edl.funcionario.id AND edl.usuario.cedula = edl.funcionario.cedula
INNER JOIN edl.dependencias_002 ON edl.funcionario.idDependencia = edl.dependencias_002.id_depto
SET
mincit_global.paa_master.responsable_dep = edl.funcionario.idDependencia,
mincit_global.paa_master.responsable_depsup = edl.dependencias_002.id_depto_superior;");
DB::Exec( $sql );




// habilita opcion de envio a administrativa

if($data['VALOR'] == $data['USOS_TOTAL'] and $data['sys_status'] == 0 )
{
$pageObject->showItem("grid_send",$recordId);
//$pageObject->hideItem("grid_edit",$recordId);
}
else
{
$pageObject->hideItem("grid_send",$recordId);
}

// habilita / deshabilita el boton editar cuando esta en modo borrador

if($data['sys_status'] == 0 )
{
$pageObject->showItem("grid_edit",$recordId);
}
else
{
$pageObject->hideItem("grid_edit",$recordId);
$pageObject->hideItem("grid_checkbox",$recordId);
}

//Colorr de la celda usos presupuestales

if ($data["USOS_TOTAL"] < $data['VALOR'])
{  
   $record["USOS_TOTAL_css"]='background:yellow;color:black';
}
if ($data["USOS_TOTAL"] > $data['VALOR'])  
{
   $record["USOS_TOTAL_css"]='background:red;color:white';
}

if ($data["USOS_TOTAL"] == $data['VALOR']) 
{ 
  $record["USOS_TOTAL_css"]='background:green;color:white';
}


// Place event code here.
// Use "Add Action" button to add code snippets.
;		
} // function BeforeMoveNextList

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record added
function AfterAdd(&$values, &$keys, $inline, &$pageObject)
{

		$sql = DB::prepareSQL("UPDATE 
mincit_global.paa_master
INNER JOIN dbusers.global_users ON mincit_global.paa_master.responsable = dbusers.global_users.Username
SET
mincit_global.paa_master.sys_user = dbusers.global_users.idusrglobal,
mincit_global.paa_master.RESPONSABLE_NOMBRE = dbusers.global_users.usr_nombresfull,
mincit_global.paa_master.RESPONSABLE_EMAIL = dbusers.global_users.usr_email,
mincit_global.paa_master.responsable = dbusers.global_users.Username;");
DB::Exec( $sql );


// Place event code here.
// Use "Add Action" button to add code snippets.
;		
} // function AfterAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>
