<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */
 
 class eventclass_paa_master_usos  extends eventsBase
{
	function __construct()
	{
	// fill list of events

		$this->events["AfterAdd"]=true;

		$this->events["AfterEdit"]=true;

		$this->events["BeforeMoveNextList"]=true;



	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record added
function AfterAdd(&$values, &$keys, $inline, &$pageObject)
{

		$sql = DB::prepareSQL("UPDATE
mincit_global.paa_master
INNER JOIN mincit_global.q_paa_total_usos ON mincit_global.paa_master.PAA_ID = mincit_global.q_paa_total_usos.PAA_ID_FK
SET
mincit_global.paa_master.USOS_TOTAL = mincit_global.q_paa_total_usos.TOTAL_USOS;");
DB::Exec( $sql );


// Place event code here.
// Use "Add Action" button to add code snippets.
;		
} // function AfterAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record updated
function AfterEdit(&$values, $where, &$oldvalues, &$keys, $inline, &$pageObject)
{

		$sql = DB::prepareSQL("UPDATE
mincit_global.paa_master
INNER JOIN mincit_global.q_paa_total_usos ON mincit_global.paa_master.PAA_ID = mincit_global.q_paa_total_usos.PAA_ID_FK
SET
mincit_global.paa_master.USOS_TOTAL = mincit_global.q_paa_total_usos.TOTAL_USOS;");
DB::Exec( $sql );

// Place event code here.
// Use "Add Action" button to add code snippets.
;		
} // function AfterEdit

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// List page: After record processed
function BeforeMoveNextList(&$data, &$row, &$record, $recordId, &$pageObject)
{

		$sql = DB::prepareSQL("UPDATE mincit_global.paa_master_usos
INNER JOIN mincit_global.paa_master ON mincit_global.paa_master_usos.PAA_ID_FK = mincit_global.paa_master.PAA_ID 
SET mincit_global.paa_master_usos.SYS_STATUS = 1 
WHERE mincit_global.paa_master.sys_status = 1;");
DB::Exec( $sql );

if($data['SYS_STATUS'] == 0 )
{
$pageObject->showItem("grid_edit",$recordId);
}
else
{
$pageObject->hideItem("grid_edit",$recordId);
$pageObject->hideItem("grid_checkbox",$recordId);
}


// Place event code here.
// Use "Add Action" button to add code snippets.
;		
} // function BeforeMoveNextList

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>
