<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */
 
 class eventclass_paa_master_admin  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["BeforeMoveNextList"]=true;

		$this->events["AfterAdd"]=true;




		$this->events["AfterEdit"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// List page: After record processed
function BeforeMoveNextList(&$data, &$row, &$record, $recordId, &$pageObject)
{

		$sql = DB::prepareSQL("UPDATE
mincit_global.paa_master
INNER JOIN mincit_global.q_paa_total_usos ON mincit_global.paa_master.PAA_ID = mincit_global.q_paa_total_usos.PAA_ID_FK
SET
mincit_global.paa_master.USOS_TOTAL = mincit_global.q_paa_total_usos.TOTAL_USOS;");
DB::Exec( $sql );

//Colorr de la celda usos presupuestales

if ($data["USOS_TOTAL"] < $data['VALOR'])
{  
   $record["USOS_TOTAL_css"]='background:yellow;color:black';
}
if ($data["USOS_TOTAL"] > $data['VALOR'])  
{
   $record["USOS_TOTAL_css"]='background:red;color:white';
}

if ($data["USOS_TOTAL"] == $data['VALOR']) 
{ 
  $record["USOS_TOTAL_css"]='background:green;color:white';
}


// Place event code here.
// Use "Add Action" button to add code snippets.
;		
} // function BeforeMoveNextList

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record added
function AfterAdd(&$values, &$keys, $inline, &$pageObject)
{

		$sql = DB::prepareSQL("UPDATE 
mincit_global.paa_master
INNER JOIN dbusers.global_users ON mincit_global.paa_master.responsable = dbusers.global_users.Username
SET
mincit_global.paa_master.sys_user = dbusers.global_users.idusrglobal,
mincit_global.paa_master.RESPONSABLE_NOMBRE = dbusers.global_users.usr_nombresfull,
mincit_global.paa_master.RESPONSABLE_EMAIL = dbusers.global_users.usr_email,
mincit_global.paa_master.responsable = dbusers.global_users.Username;");
DB::Exec( $sql );


// Place event code here.
// Use "Add Action" button to add code snippets.
;		
} // function AfterAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record updated
function AfterEdit(&$values, $where, &$oldvalues, &$keys, $inline, &$pageObject)
{

		$sql = DB::prepareSQL("UPDATE 
mincit_global.paa_master
INNER JOIN dbusers.global_users ON mincit_global.paa_master.responsable = dbusers.global_users.Username
SET
mincit_global.paa_master.sys_user = dbusers.global_users.idusrglobal,
mincit_global.paa_master.RESPONSABLE_NOMBRE = dbusers.global_users.usr_nombresfull,
mincit_global.paa_master.RESPONSABLE_EMAIL = dbusers.global_users.usr_email,
mincit_global.paa_master.responsable = dbusers.global_users.Username;");
DB::Exec( $sql );

// Place event code here.
// Use "Add Action" button to add code snippets.
;		
} // function AfterEdit

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>
