<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */
 
 class eventclass_paa_master_ct  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["AfterAdd"]=true;

		$this->events["AfterEdit"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record added
function AfterAdd(&$values, &$keys, $inline, &$pageObject)
{

		
$sql = DB::prepareSQL("UPDATE
dbct.contrato
INNER JOIN mincit_global.paa_master_ct ON dbct.contrato.id_cont = mincit_global.paa_master_ct.CONT_ID_FK
INNER JOIN mincit_global.q_export_secop_status_0_wrubro ON mincit_global.paa_master_ct.PAA_ID_FK = mincit_global.q_export_secop_status_0_wrubro.PAA_ID
SET
dbct.contrato.cont_paa_id = mincit_global.paa_master_ct.PAA_ID_FK,
dbct.contrato.cont_catalogo_presupuestal = mincit_global.q_export_secop_status_0_wrubro.USO_CONTABILIDAD_B;");
DB::Exec( $sql );

// Place event code here.
// Use "Add Action" button to add code snippets.
;		
} // function AfterAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record updated
function AfterEdit(&$values, $where, &$oldvalues, &$keys, $inline, &$pageObject)
{

		$sql = DB::prepareSQL("UPDATE
dbct.contrato
INNER JOIN mincit_global.paa_master_ct ON dbct.contrato.id_cont = mincit_global.paa_master_ct.CONT_ID_FK
INNER JOIN mincit_global.q_export_secop_status_0_wrubro ON mincit_global.paa_master_ct.PAA_ID_FK = mincit_global.q_export_secop_status_0_wrubro.PAA_ID
SET
dbct.contrato.cont_paa_id = mincit_global.paa_master_ct.PAA_ID_FK,
dbct.contrato.cont_catalogo_presupuestal = mincit_global.q_export_secop_status_0_wrubro.USO_CONTABILIDAD_B;");
DB::Exec( $sql );

// Place event code here.
// Use "Add Action" button to add code snippets.
;		
} // function AfterEdit

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>
